#!/usr/bin/env python3
"""
Tool Generator — Creates 210 tools across 10 categories.
Each tool gets its own directory with a tool.json and handler.js.
"""
import os
import json

TOOLS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "tools")

# Import tool configs
try:
    from tool_configs import TOOL_CONFIGS
except ImportError:
    TOOL_CONFIGS = {}

# ─────────────────────────────────────────────────────────────
# Category Definitions
# ─────────────────────────────────────────────────────────────

CATEGORIES = {
    "text": {
        "name": "Text Tools",
        "icon": "text_fields",
        "tools": [
            ("word-counter", "Word Counter", "Count words, characters, sentences, paragraphs, and reading time", "text", "Paste your text here...", "Count", "calculate"),
            ("char-counter", "Character Counter", "Count characters with and without spaces, lines, and bytes", "text", "Paste your text here...", "Count", "calculate"),
            ("sentence-counter", "Sentence Counter", "Count sentences and words per sentence in your text", "text", "Paste your text here...", "Count", "calculate"),
            ("paragraph-counter", "Paragraph Counter", "Count paragraphs, lines, and words per paragraph", "text", "Paste your text here...", "Count", "calculate"),
            ("reading-time", "Reading Time Calculator", "Estimate reading time and speech duration for any text", "text", "Paste your text here...", "Calculate", "schedule"),
            ("case-converter", "Case Converter", "Convert text to UPPERCASE, lowercase, Title Case, Sentence case, aLtErNaTiNg CaSe, or iNVERSE cAsE", "text", "Paste your text here...", "Convert", "text_format"),
            ("text-reverser", "Text Reverser", "Reverse text, words, sentences, or characters with various options", "text", "Paste your text here...", "Reverse", "flip"),
            ("text-duplicator", "Text Duplicator", "Duplicate text multiple times with custom separators", "text", "Paste your text here...", "Duplicate", "content_copy"),
            ("line-sorter", "Line Sorter", "Sort lines alphabetically, by length, reverse order, or remove duplicates", "text", "Paste your text here...", "Sort", "sort"),
            ("line-numberer", "Line Numberer", "Add line numbers to text with custom starting number and format", "text", "Paste your text here...", "Number", "format_list_numbered"),
            ("find-replace", "Find and Replace", "Find and replace text with regex support and case-insensitive matching", "text", "Paste your text here...", "Replace", "find_replace"),
            ("text-cleaner", "Text Cleaner", "Remove extra spaces, blank lines, special characters, and normalize whitespace", "text", "Paste your text here...", "Clean", "auto_fix_high"),
            ("text-trimmer", "Text Trimmer", "Trim text to a specific character or word limit with ellipsis", "text", "Paste your text here...", "Trim", "content_cut"),
            ("word-frequency", "Word Frequency Analyzer", "Analyze word frequency, find most common words, and generate word clouds data", "text", "Paste your text here...", "Analyze", "analytics"),
            ("text-diff", "Text Difference Checker", "Compare two texts and highlight differences line by line or word by word", "text", "Paste text here...", "Compare", "compare"),
            ("lorem-ipsum", "Lorem Ipsum Generator", "Generate placeholder text in paragraphs, words, or sentences", "text", "Enter number of paragraphs...", "Generate", "dynamic_feed"),
            ("palindrome-checker", "Palindrome Checker", "Check if text is a palindrome ignoring spaces, punctuation, and case", "text", "Enter text to check...", "Check", "check_circle"),
            ("text-stats", "Text Statistics", "Comprehensive text analysis: syllables, complex words, formality score", "text", "Paste your text here...", "Analyze", "insights"),
            ("name-generator", "Name Generator", "Generate random first names, last names, full names, usernames, or passwords", "text", "Enter prefix or seed (optional)...", "Generate", "person_add"),
            ("text-encoder", "Text Encoder/Decoder", "Encode/decode text with Base64, URL encoding, HTML entities, or ROT13", "text", "Enter text to encode/decode...", "Encode", "lock"),
            ("emoji-picker", "Emoji Converter", "Convert text descriptions to emojis or find emojis by keyword", "text", "Enter text or emoji keyword...", "Convert", "emoji_emotions"),
            ("acronym-generator", "Acronym Generator", "Generate acronyms from phrases and text", "text", "Enter a phrase...", "Generate", "short_text"),
            ("text-summarizer", "Text Summarizer", "Extractive summarization — find the most important sentences", "text", "Paste your text here...", "Summarize", "summarize"),
            ("rewriter", "Text Rewriter", "Rewrite text with different tones: formal, casual, professional, friendly", "text", "Paste your text here...", "Rewrite", "edit"),
            ("plagiarism-checker", "Text Similarity Checker", "Check text similarity and detect potential duplicate content", "text", "Paste text to analyze...", "Check", "gpp_good"),
            ("text-to-slugs", "Text to Slug Generator", "Convert text to URL-friendly slugs with custom separators", "text", "Enter title or heading...", "Generate", "link"),
            ("binary-text", "Binary ↔ Text Converter", "Convert text to binary and binary back to text", "text", "Enter text or binary...", "Convert", "code"),
            ("morse-code", "Morse Code Converter", "Convert text to morse code and morse code back to text", "text", "Enter text or morse code...", "Convert", "radio"),
            ("pig-latin", "Pig Latin Translator", "Convert English text to Pig Latin and back", "text", "Enter text to translate...", "Translate", "record_voice_over"),
            ("markdown-preview", "Markdown Preview", "Live preview of Markdown with syntax highlighting", "text", "Enter Markdown text...", "Preview", "preview"),
        ],
    },
    "code": {
        "name": "Code Tools",
        "icon": "code",
        "tools": [
            ("json-formatter", "JSON Formatter", "Format, validate, and beautify JSON data with syntax highlighting", "text", "Paste JSON here...", "Format", "data_object"),
            ("json-validator", "JSON Validator", "Validate JSON and find syntax errors with line numbers", "text", "Paste JSON here...", "Validate", "check_circle"),
            ("json-minifier", "JSON Minifier", "Minify JSON by removing whitespace and line breaks", "text", "Paste JSON here...", "Minify", "compress"),
            ("json-to-csv", "JSON to CSV Converter", "Convert JSON arrays to CSV format with customizable delimiters", "text", "Paste JSON array here...", "Convert", "table_chart"),
            ("csv-to-json", "CSV to JSON Converter", "Convert CSV data to JSON format with headers as keys", "text", "Paste CSV data here...", "Convert", "data_object"),
            ("xml-formatter", "XML Formatter", "Format and beautify XML with proper indentation", "text", "Paste XML here...", "Format", "code"),
            ("xml-validator", "XML Validator", "Validate XML syntax and find errors", "text", "Paste XML here...", "Validate", "check_circle"),
            ("xml-to-json", "XML to JSON Converter", "Convert XML documents to JSON format", "text", "Paste XML here...", "Convert", "data_object"),
            ("json-to-xml", "JSON to XML Converter", "Convert JSON data to XML format", "text", "Paste JSON here...", "Convert", "code"),
            ("yaml-formatter", "YAML Formatter", "Format and validate YAML documents", "text", "Paste YAML here...", "Format", "code"),
            ("html-formatter", "HTML Formatter", "Format and beautify HTML with proper indentation", "text", "Paste HTML here...", "Format", "code"),
            ("html-minifier", "HTML Minifier", "Minify HTML by removing whitespace, comments, and unnecessary attributes", "text", "Paste HTML here...", "Minify", "compress"),
            ("css-formatter", "CSS Formatter", "Format and beautify CSS stylesheets", "text", "Paste CSS here...", "Format", "code"),
            ("css-minifier", "CSS Minifier", "Minify CSS by removing whitespace and comments", "text", "Paste CSS here...", "Minify", "compress"),
            ("css-to-scss", "CSS to SCSS Converter", "Convert CSS to SCSS with variables and nesting suggestions", "text", "Paste CSS here...", "Convert", "code"),
            ("js-formatter", "JavaScript Formatter", "Format and beautify JavaScript code", "text", "Paste JavaScript here...", "Format", "code"),
            ("js-minifier", "JavaScript Minifier", "Minify JavaScript code", "text", "Paste JavaScript here...", "Minify", "compress"),
            ("js-beautifier", "JavaScript Beautifier", "Beautify obfuscated or minified JavaScript", "text", "Paste JavaScript here...", "Beautify", "auto_fix_high"),
            ("sql-formatter", "SQL Formatter", "Format SQL queries with proper indentation and keyword highlighting", "text", "Paste SQL here...", "Format", "data_object"),
            ("sql-validator", "SQL Validator", "Validate SQL syntax and detect common errors", "text", "Paste SQL here...", "Validate", "check_circle"),
            ("python-formatter", "Python Formatter", "Format Python code with proper PEP 8 style", "text", "Paste Python code here...", "Format", "code"),
            ("regex-tester", "Regex Tester", "Test regular expressions with real-time matching and explanation", "text", "Enter regex pattern...", "Test", "find_replace"),
            ("regex-generator", "Regex Generator", "Generate regular expressions from descriptions", "text", "Describe what to match...", "Generate", "find_replace"),
            ("markdown-to-html", "Markdown to HTML", "Convert Markdown to clean HTML", "text", "Enter Markdown here...", "Convert", "code"),
            ("html-to-markdown", "HTML to Markdown", "Convert HTML to Markdown format", "text", "Paste HTML here...", "Convert", "code"),
            ("code-beautifier", "Code Beautifier", "Auto-detect language and beautify code", "text", "Paste code here...", "Beautify", "auto_fix_high"),
            ("code-minifier", "Code Minifier", "Auto-detect language and minify code", "text", "Paste code here...", "Minify", "compress"),
            ("code-obfuscator", "Code Obfuscator", "Obfuscate JavaScript/TypeScript code with variable renaming", "text", "Paste code here...", "Obfuscate", "security"),
            ("code-documenter", "Code Documenter", "Generate JSDoc/Docstring comments for functions", "text", "Paste code here...", "Document", "description"),
            ("sort-lines", "Sort Lines", "Sort lines alphabetically, by length, numerically, or randomly", "text", "Paste lines here...", "Sort", "sort"),
            ("deduplicate-lines", "Remove Duplicate Lines", "Remove exact and fuzzy duplicate lines from text", "text", "Paste text here...", "Remove Duplicates", "delete_sweep"),
            ("base64-encode", "Base64 Encoder/Decoder", "Encode and decode Base64 strings", "text", "Enter text or Base64...", "Convert", "lock"),
            ("url-encode", "URL Encoder/Decoder", "Encode and decode URLs and query parameters", "text", "Enter URL or encoded string...", "Convert", "link"),
            ("html-entity-encode", "HTML Entity Encoder", "Encode/decode HTML special characters and entities", "text", "Enter text or HTML entities...", "Convert", "code"),
            ("jwt-decoder", "JWT Token Decoder", "Decode JWT tokens and view header, payload, and signature", "text", "Paste JWT token here...", "Decode", "vpn_key"),
            ("color-converter", "Color Format Converter", "Convert between HEX, RGB, HSL, and CMYK color formats", "text", "Enter color value (HEX, RGB, HSL)...", "Convert", "palette"),
        ],
    },
    "crypto": {
        "name": "Cryptography",
        "icon": "enhanced_encryption",
        "tools": [
            ("hash-generator", "Hash Generator", "Generate MD5, SHA-1, SHA-256, SHA-512, CRC32 hashes from text", "select", "Select algorithm...", "Generate", "fingerprint"),
            ("md5-generator", "MD5 Hash Generator", "Generate MD5 hash from any text input", "text", "Enter text to hash...", "Generate", "fingerprint"),
            ("sha1-generator", "SHA-1 Hash Generator", "Generate SHA-1 hash from any text input", "text", "Enter text to hash...", "Generate", "fingerprint"),
            ("sha256-generator", "SHA-256 Hash Generator", "Generate SHA-256 hash from any text input", "text", "Enter text to hash...", "Generate", "fingerprint"),
            ("sha512-generator", "SHA-512 Hash Generator", "Generate SHA-512 hash from any text input", "text", "Enter text to hash...", "Generate", "fingerprint"),
            ("hmac-generator", "HMAC Generator", "Generate HMAC with MD5, SHA-1, SHA-256, or SHA-512", "text", "Enter message...", "Generate", "fingerprint"),
            ("bcrypt-generator", "Bcrypt Hash Generator", "Generate bcrypt password hashes with custom cost factor", "text", "Enter password to hash...", "Generate", "lock"),
            ("password-generator", "Password Generator", "Generate strong passwords with custom length, character types, and exclusion rules", "text", "Optional notes...", "Generate", "vpn_key"),
            ("uuid-generator", "UUID Generator", "Generate UUID v1, v4, or custom format UUIDs in bulk", "text", "Optional seed or prefix...", "Generate", "tag"),
            ("token-generator", "Token Generator", "Generate secure random tokens, API keys, and session IDs", "text", "Optional prefix...", "Generate", "key"),
            ("hash-checker", "Hash Checker", "Verify if a hash matches given input text", "text", "Enter hash to check...", "Verify", "gpp_good"),
            ("caesar-cipher", "Caesar Cipher", "Encrypt and decrypt text using Caesar cipher with custom shift", "text", "Enter text to encrypt/decrypt...", "Process", "lock"),
            ("rot13", "ROT13 Encoder/Decoder", "Encode and decode text using ROT13 substitution", "text", "Enter text to encode/decode...", "Process", "swap_horiz"),
            ("atbash-cipher", "Atbash Cipher", "Encode and decode text using the Atbash substitution cipher", "text", "Enter text to encode/decode...", "Process", "swap_horiz"),
            ("vigenere-cipher", "Vigenère Cipher", "Encrypt and decrypt using the Vigenère polyalphabetic cipher", "text", "Enter text...", "Process", "lock"),
            ("morse-code-crypto", "Morse Code Encoder/Decoder", "Encode and decode messages using International Morse Code", "text", "Enter text or morse code...", "Convert", "radio"),
            ("binary-encoder", "Binary Encoder/Decoder", "Convert text to binary and binary to text", "text", "Enter text or binary...", "Convert", "memory"),
            ("hex-encoder", "Hex Encoder/Decoder", "Convert text to hexadecimal and back", "text", "Enter text or hex...", "Convert", "code"),
            ("ascii-table", "ASCII Table Viewer", "View ASCII character table with decimal, hex, octal, and binary values", "text", "Search character or code...", "View", "table"),
            ("unicode-converter", "Unicode Converter", "Convert text to Unicode code points and back", "text", "Enter text or Unicode code points...", "Convert", "translate"),
            ("password-strength", "Password Strength Checker", "Analyze password strength with entropy calculation and crack time estimation", "text", "Enter password to analyze...", "Check", "security"),
            ("2fa-generator", "2FA Code Generator", "Generate TOTP two-factor authentication codes from secret keys", "text", "Enter TOTP secret key...", "Generate", "security"),
            ("brainfuck", "Brainfuck Interpreter", "Execute Brainfuck code and see output", "text", "Enter Brainfuck code...", "Run", "play_arrow"),
            ("leet-speak", "Leet Speak Translator", "Convert text to 1337 5p34k and back", "text", "Enter text...", "Convert", "translate"),
        ],
    },
    "calculators": {
        "name": "Calculators",
        "icon": "calculate",
        "tools": [
            ("scientific-calculator", "Scientific Calculator", "Advanced calculator with trigonometry, logarithms, exponents, and more", "text", "Enter expression (e.g. sin(45) + log(100))...", "Calculate", "calculate"),
            ("percentage-calculator", "Percentage Calculator", "Calculate percentages, percentage increase/decrease, and percentage of values", "text", "Enter percentage problem (e.g. 25% of 200)...", "Calculate", "calculate"),
            ("tip-calculator", "Tip Calculator", "Calculate tips and split bills with custom tip percentages", "text", "Enter bill amount...", "Calculate", "calculate"),
            ("loan-calculator", "Loan Calculator", "Calculate monthly payments, total interest, and amortization schedules", "text", "Enter loan amount...", "Calculate", "calculate"),
            ("mortgage-calculator", "Mortgage Calculator", "Calculate mortgage payments, total cost, and interest over loan term", "text", "Enter home price...", "Calculate", "calculate"),
            ("compound-interest", "Compound Interest Calculator", "Calculate compound interest with regular contributions over time", "text", "Enter principal amount...", "Calculate", "calculate"),
            ("bmi-calculator", "BMI Calculator", "Calculate Body Mass Index from height and weight", "text", "Enter weight (kg) and height (cm)...", "Calculate", "calculate"),
            ("calorie-calculator", "Calorie Calculator", "Calculate daily calorie needs based on activity level and goals", "text", "Enter weight (kg), height (cm), age...", "Calculate", "calculate"),
            ("age-calculator", "Age Calculator", "Calculate exact age in years, months, days, hours, and minutes", "text", "Enter birth date (YYYY-MM-DD)...", "Calculate", "calculate"),
            ("date-calculator", "Date Calculator", "Add or subtract days, weeks, months from a date", "text", "Enter start date and days to add/subtract...", "Calculate", "calculate"),
            ("days-between", "Days Between Dates", "Calculate the number of days between two dates", "text", "Enter start date and end date...", "Calculate", "calculate"),
            ("area-calculator", "Area Calculator", "Calculate area of circle, rectangle, triangle, trapezoid, and parallelogram", "text", "Enter dimensions...", "Calculate", "calculate"),
            ("volume-calculator", "Volume Calculator", "Calculate volume of sphere, cylinder, cone, cube, and rectangular prism", "text", "Enter dimensions...", "Calculate", "calculate"),
            ("pythagorean", "Pythagorean Theorem", "Calculate the missing side of a right triangle", "text", "Enter two sides (a, b or c)...", "Calculate", "calculate"),
            ("quadratic-solver", "Quadratic Equation Solver", "Solve quadratic equations ax² + bx + c = 0 with step-by-step solutions", "text", "Enter coefficients a, b, c...", "Solve", "calculate"),
            ("linear-solver", "Linear Equation Solver", "Solve linear equations and systems of equations", "text", "Enter equation (e.g. 2x + 3 = 7)...", "Solve", "calculate"),
            ("unit-converter", "Unit Converter", "Convert between metric and imperial units for length, weight, temperature, and more", "text", "Enter value and units (e.g. 100 kg to lbs)...", "Convert", "calculate"),
            ("temperature-converter", "Temperature Converter", "Convert between Celsius, Fahrenheit, and Kelvin", "text", "Enter temperature (e.g. 100 C)...", "Convert", "thermostat"),
            ("currency-converter", "Currency Converter", "Convert between currencies using latest rates (offline rates)", "text", "Enter amount and currencies (e.g. 100 USD to EUR)...", "Convert", "payments"),
            ("speed-converter", "Speed Converter", "Convert between km/h, mph, m/s, and knots", "text", "Enter speed and units...", "Convert", "speed"),
            ("data-converter", "Data Size Converter", "Convert between bytes, KB, MB, GB, TB, PB", "text", "Enter data size...", "Convert", "data_usage"),
            ("time-converter", "Time Converter", "Convert between seconds, minutes, hours, days, weeks", "text", "Enter time value...", "Convert", "schedule"),
            ("number-base", "Number Base Converter", "Convert between binary, octal, decimal, and hexadecimal", "text", "Enter number to convert...", "Convert", "swap_horiz"),
            ("scientific-notation", "Scientific Notation Converter", "Convert between standard and scientific notation", "text", "Enter number...", "Convert", "science"),
            ("roman-numeral", "Roman Numeral Converter", "Convert between Roman numerals and Arabic numbers", "text", "Enter Roman numeral or number...", "Convert", "roman"),
            ("factorial-calculator", "Factorial Calculator", "Calculate factorials and permutations", "text", "Enter number...", "Calculate", "calculate"),
            ("fibonacci", "Fibonacci Calculator", "Generate Fibonacci sequences and find specific terms", "text", "Enter number of terms...", "Generate", "timeline"),
            ("prime-checker", "Prime Number Checker", "Check if a number is prime and find prime factors", "text", "Enter number...", "Check", "check_circle"),
            ("gcd-lcm", "GCD & LCM Calculator", "Calculate Greatest Common Divisor and Least Common Multiple", "text", "Enter two numbers...", "Calculate", "calculate"),
            ("hex-calculator", "Hexadecimal Calculator", "Perform arithmetic operations in hexadecimal", "text", "Enter hex expression...", "Calculate", "calculate"),
            ("binary-calculator", "Binary Calculator", "Perform arithmetic operations in binary", "text", "Enter binary expression...", "Calculate", "calculate"),
            ("electricity-calculator", "Electricity Cost Calculator", "Calculate electricity costs based on wattage and usage time", "text", "Enter wattage and hours per day...", "Calculate", "bolt"),
        ],
    },
    "generators": {
        "name": "Generators",
        "icon": "auto_awesome",
        "tools": [
            ("random-password", "Random Password Generator", "Generate cryptographically strong random passwords", "text", "Optional notes...", "Generate", "vpn_key"),
            ("random-number", "Random Number Generator", "Generate random numbers within a range with distribution options", "text", "Enter range (e.g. 1-100)...", "Generate", "casino"),
            ("random-string", "Random String Generator", "Generate random strings with custom character sets and length", "text", "Enter length...", "Generate", "shuffle"),
            ("random-color", "Random Color Generator", "Generate random colors in HEX, RGB, and HSL formats", "text", "Optional seed...", "Generate", "palette"),
            ("random-name", "Random Name Generator", "Generate random full names, first names, or last names", "text", "Optional count...", "Generate", "person"),
            ("random-email", "Random Email Generator", "Generate random email addresses for testing", "text", "Optional domain...", "Generate", "email"),
            ("random-address", "Random Address Generator", "Generate realistic random addresses for testing", "text", "Optional country...", "Generate", "home"),
            ("random-phone", "Random Phone Number Generator", "Generate random phone numbers in various formats", "text", "Optional country code...", "Generate", "phone"),
            ("random-date", "Random Date Generator", "Generate random dates within a range", "text", "Optional range (YYYY-MM-DD)...", "Generate", "event"),
            ("random-boolean", "Random Boolean Generator", "Generate random true/false values with fair distribution", "text", "Optional count...", "Generate", "check_circle"),
            ("uuid-v4", "UUID v4 Generator", "Generate random UUID v4 identifiers", "text", "Optional count...", "Generate", "tag"),
            ("cuid-generator", "CUID Generator", "Generate Collision-resistant Unique IDs", "text", "Optional count...", "Generate", "tag"),
            ("nanoid-generator", "NanoID Generator", "Generate compact unique IDs with custom alphabet and length", "text", "Optional length...", "Generate", "tag"),
            ("sequential-id", "Sequential ID Generator", "Generate sequential IDs with custom prefix and padding", "text", "Enter prefix...", "Generate", "tag"),
            ("lorem-paragraphs", "Lorem Ipsum Paragraphs", "Generate Lorem Ipsum placeholder paragraphs", "text", "Number of paragraphs...", "Generate", "dynamic_feed"),
            ("lorem-words", "Lorem Ipsum Words", "Generate Lorem Ipsum placeholder words", "text", "Number of words...", "Generate", "dynamic_feed"),
            ("lorem-sentences", "Lorem Ipsum Sentences", "Generate Lorem Ipsum placeholder sentences", "text", "Number of sentences...", "Generate", "dynamic_feed"),
            ("fake-user", "Fake User Profile Generator", "Generate complete fake user profiles with names, emails, addresses", "text", "Optional count...", "Generate", "person"),
            ("fake-product", "Fake Product Data Generator", "Generate fake product names, descriptions, prices, and SKUs", "text", "Optional count...", "Generate", "inventory_2"),
            ("fake-company", "Fake Company Generator", "Generate fake company names, domains, and descriptions", "text", "Optional count...", "Generate", "business"),
            ("qr-code", "QR Code Generator", "Generate QR codes for text, URLs, emails, or WiFi credentials", "text", "Enter content for QR code...", "Generate", "qr_code_2"),
            ("barcode", "Barcode Generator", "Generate barcodes in Code128, Code39, EAN13 formats", "text", "Enter data to encode...", "Generate", "barcode"),
            ("placeholder-image", "Placeholder Image Generator", "Generate placeholder images with custom dimensions and colors", "text", "Enter dimensions (e.g. 300x200)...", "Generate", "image"),
            ("gradient-generator", "CSS Gradient Generator", "Generate CSS linear, radial, and conic gradients", "text", "Optional preset name...", "Generate", "gradient"),
            ("box-shadow", "CSS Box Shadow Generator", "Generate CSS box-shadow values with preview", "text", "Optional preset...", "Generate", "shadow"),
            ("text-shadow", "CSS Text Shadow Generator", "Generate CSS text-shadow values with preview", "text", "Optional preset...", "Generate", "text_fields"),
            ("css-animation", "CSS Animation Generator", "Generate CSS keyframe animations for common effects", "text", "Describe animation...", "Generate", "animation"),
            ("responsive-breakpoint", "Responsive Breakpoint Generator", "Generate CSS media query breakpoints for common devices", "text", "Optional custom width...", "Generate", "devices"),
            ("color-palette", "Color Palette Generator", "Generate harmonious color palettes from a base color", "text", "Enter base color (HEX)...", "Generate", "palette"),
            ("random-fortune", "Random Fortune Generator", "Generate random motivational quotes and fortunes", "text", "Optional theme...", "Generate", "format_quote"),
            ("dice-roller", "Dice Roller", "Roll dice with custom sides, count, and modifiers", "text", "Enter dice notation (e.g. 2d6+3)...", "Roll", "casino"),
            ("coin-flip", "Coin Flip Simulator", "Flip coins with custom counts and display patterns", "text", "Optional count...", "Flip", "swap_horiz"),
            ("random-unit", "Random Unit of Measurement", "Generate random measurements in various unit systems", "text", "Optional unit type...", "Generate", "straighten"),
            ("font-generator", "Font Style Generator", "Convert text to various Unicode font styles", "text", "Enter text to stylize...", "Generate", "font_download"),
            ("micro-uuid", "Micro ID Generator", "Generate short 6-8 character unique IDs", "text", "Optional length...", "Generate", "tag"),
            ("password-memorable", "Memorable Password Generator", "Generate pronounceable passwords using word combinations", "text", "Optional word count...", "Generate", "vpn_key"),
        ],
    },
    "converters": {
        "name": "Converters",
        "icon": "swap_horiz",
        "tools": [
            ("text-to-html", "Text to HTML", "Convert plain text to formatted HTML with line breaks and paragraphs", "text", "Enter plain text...", "Convert", "code"),
            ("html-to-text", "HTML to Text", "Strip HTML tags and extract plain text content", "text", "Paste HTML here...", "Convert", "text_fields"),
            ("text-to-css", "Text to CSS", "Convert text to CSS font styles, gradients, and text effects", "text", "Enter text...", "Convert", "code"),
            ("text-to-svg", "Text to SVG", "Convert text to SVG format with custom fonts and colors", "text", "Enter text...", "Convert", "code"),
            ("csv-to-markdown", "CSV to Markdown Table", "Convert CSV data to Markdown table format", "text", "Paste CSV data...", "Convert", "table_chart"),
            ("markdown-to-csv", "Markdown Table to CSV", "Convert Markdown tables to CSV format", "text", "Paste Markdown table...", "Convert", "table_chart"),
            ("json-to-yaml", "JSON to YAML Converter", "Convert JSON to YAML format", "text", "Paste JSON here...", "Convert", "code"),
            ("yaml-to-json", "YAML to JSON Converter", "Convert YAML to JSON format", "text", "Paste YAML here...", "Convert", "data_object"),
            ("json-to-toml", "JSON to TOML Converter", "Convert JSON to TOML format", "text", "Paste JSON here...", "Convert", "code"),
            ("toml-to-json", "TOML to JSON Converter", "Convert TOML to JSON format", "text", "Paste TOML here...", "Convert", "data_object"),
            ("json-to-typescript", "JSON to TypeScript Interface", "Generate TypeScript interfaces from JSON data", "text", "Paste JSON here...", "Convert", "code"),
            ("json-to-python", "JSON to Python Class", "Generate Python dataclass from JSON data", "text", "Paste JSON here...", "Convert", "code"),
            ("json-to-go-struct", "JSON to Go Struct", "Generate Go struct definitions from JSON data", "text", "Paste JSON here...", "Convert", "code"),
            ("json-to-sql", "JSON to SQL Insert", "Generate SQL INSERT statements from JSON data", "text", "Paste JSON here...", "Convert", "data_object"),
            ("csv-to-sql", "CSV to SQL", "Generate SQL CREATE TABLE and INSERT statements from CSV", "text", "Paste CSV data...", "Convert", "data_object"),
            ("xml-to-yaml", "XML to YAML Converter", "Convert XML to YAML format", "text", "Paste XML here...", "Convert", "code"),
            ("yaml-to-xml", "YAML to XML Converter", "Convert YAML to XML format", "text", "Paste YAML here...", "Convert", "code"),
            ("regex-to-nfa", "Regex to NFA Diagram", "Convert regex to NFA state diagram description", "text", "Enter regex pattern...", "Convert", "account_tree"),
            ("cron-parser", "Cron Expression Parser", "Parse cron expressions and show next execution times", "text", "Enter cron expression...", "Parse", "schedule"),
            ("timestamp-converter", "Timestamp Converter", "Convert Unix timestamps to human-readable dates and back", "text", "Enter timestamp or date...", "Convert", "schedule"),
            ("timezone-converter", "Timezone Converter", "Convert times between different timezones", "text", "Enter time and timezone...", "Convert", "public"),
            ("emoji-to-text", "Emoji to Text Description", "Convert emoji to text descriptions and names", "text", "Enter emoji...", "Convert", "emoji_emotions"),
            ("number-to-words", "Number to Words", "Convert numbers to written English words", "text", "Enter number...", "Convert", "text_fields"),
            ("words-to-number", "Words to Number", "Convert written English numbers to digits", "text", "Enter words...", "Convert", "calculate"),
            ("roman-to-arabic", "Roman to Arabic Converter", "Convert Roman numerals to Arabic numbers", "text", "Enter Roman numeral...", "Convert", "swap_horiz"),
            ("arabic-to-roman", "Arabic to Roman Converter", "Convert Arabic numbers to Roman numerals", "text", "Enter number...", "Convert", "swap_horiz"),
            ("color-to-css", "Color to CSS", "Convert color values to CSS code snippets", "text", "Enter color (HEX, RGB, HSL)...", "Convert", "palette"),
            ("css-to-text", "CSS to Plain Text", "Convert CSS selectors and properties to readable text", "text", "Paste CSS here...", "Convert", "text_fields"),
            ("image-to-base64", "Image to Base64", "Convert uploaded images to Base64 encoded strings", "text", "Upload image or paste Base64...", "Convert", "image"),
            ("text-to-image", "Text to Image", "Convert text to a downloadable PNG image with custom styling", "text", "Enter text to render...", "Generate", "image"),
            ("font-converter", "Font Format Converter", "Convert text to CSS @font-face declarations", "text", "Enter font name...", "Convert", "font_download"),
            ("svg-to-css", "SVG to CSS Background", "Convert SVG to CSS background-image data URI", "text", "Paste SVG here...", "Convert", "code"),
            ("json-to-env", "JSON to Environment Variables", "Convert JSON config to .env file format", "text", "Paste JSON here...", "Convert", "code"),
            ("env-to-json", "Environment Variables to JSON", "Convert .env file format to JSON", "text", "Paste env vars...", "Convert", "data_object"),
            ("sql-to-json", "SQL to JSON Converter", "Convert SQL CREATE TABLE statements to JSON schemas", "text", "Paste SQL here...", "Convert", "data_object"),
            ("graphql-to-rest", "GraphQL to REST Converter", "Convert GraphQL queries to REST API endpoint descriptions", "text", "Paste GraphQL query...", "Convert", "code"),
        ],
    },
    "web": {
        "name": "Web & SEO",
        "icon": "public",
        "tools": [
            ("url-encoder-tool", "URL Encoder/Decoder", "Encode and decode URLs, query strings, and path components", "text", "Enter URL to encode/decode...", "Convert", "link"),
            ("url-parser", "URL Parser", "Parse URL into protocol, hostname, port, path, query, and hash", "text", "Enter URL to parse...", "Parse", "link"),
            ("url-builder", "URL Builder", "Build URLs from components with query parameter management", "text", "Enter base URL...", "Build", "link"),
            ("query-string", "Query String Builder", "Build and parse URL query parameters", "text", "Enter parameters...", "Build", "link"),
            ("meta-tag-generator", "Meta Tag Generator", "Generate HTML meta tags for SEO, social media, and accessibility", "text", "Enter page title...", "Generate", "code"),
            ("open-graph-generator", "Open Graph Generator", "Generate Open Graph meta tags for social sharing", "text", "Enter page title...", "Generate", "share"),
            ("twitter-card-generator", "Twitter Card Generator", "Generate Twitter Card meta tags", "text", "Enter tweet content...", "Generate", "share"),
            ("robots-txt-generator", "Robots.txt Generator", "Generate robots.txt with crawl rules and sitemap references", "text", "Enter sitemap URL...", "Generate", "smart_toy"),
            ("sitemap-generator", "Sitemap XML Generator", "Generate sitemap.xml for websites", "text", "Enter site URLs (one per line)...", "Generate", "map"),
            ("structured-data", "Structured Data Generator", "Generate JSON-LD structured data for Schema.org", "text", "Enter entity type...", "Generate", "code"),
            ("html-encoder", "HTML Encoder/Decoder", "Encode and decode HTML entities and special characters", "text", "Enter HTML text...", "Convert", "code"),
            ("css-selector", "CSS Selector Generator", "Generate CSS selectors from element descriptions", "text", "Describe element...", "Generate", "code"),
            ("htaccess-generator", ".htaccess Generator", "Generate Apache .htaccess rules for redirects and security", "text", "Enter redirect path...", "Generate", "code"),
            ("ssl-checker", "SSL Certificate Info", "Display SSL certificate information and chain details", "text", "Enter domain name...", "Check", "security"),
            ("dns-checker", "DNS Lookup Tool", "Look up DNS records for a domain", "text", "Enter domain name...", "Lookup", "dns"),
            ("whois-lookup", "WHOIS Lookup", "Look up WHOIS registration information for domains", "text", "Enter domain name...", "Lookup", "search"),
            ("ip-lookup", "IP Address Lookup", "Get geolocation and ISP information for IP addresses", "text", "Enter IP address...", "Lookup", "location_on"),
            ("user-agent-parser", "User Agent Parser", "Parse user agent strings to extract browser, OS, and device info", "text", "Enter user agent string...", "Parse", "devices"),
            ("viewport-resizer", "Viewport Resizer", "Preview how websites look at different screen sizes", "text", "Enter screen width...", "Preview", "devices"),
            ("cookie-parser", "Cookie String Parser", "Parse cookie header strings into individual cookie objects", "text", "Enter cookie string...", "Parse", "cookie"),
            ("http-header-viewer", "HTTP Header Viewer", "Parse and display HTTP header strings", "text", "Enter HTTP headers...", "Parse", "http"),
            ("json-ld-viewer", "JSON-LD Viewer", "Validate and display JSON-LD structured data", "text", "Paste JSON-LD here...", "Validate", "code"),
            ("redirect-checker", "Redirect Checker", "Check redirect chains and final destination URLs", "text", "Enter URL to check...", "Check", "swap_horiz"),
            ("page-size-checker", "Page Size Calculator", "Estimate page size from HTML content", "text", "Paste HTML here...", "Calculate", "data_usage"),
            ("word-count-seo", "SEO Word Counter", "Count words and analyze SEO metrics for web content", "text", "Paste article content...", "Analyze", "analytics"),
            ("readability-score", "Readability Score Calculator", "Calculate Flesch-Kincaid, Coleman-Liau, and Gunning Fog scores", "text", "Paste text here...", "Analyze", "analytics"),
            ("json-sitemap", "JSON to Sitemap", "Convert URL lists to XML sitemap format", "text", "Enter URLs (one per line)...", "Convert", "map"),
            ("base64-url-embed", "Base64 URL Embed Generator", "Create data: URI from text content", "text", "Enter text to embed...", "Generate", "link"),
            ("csp-generator", "CSP Header Generator", "Generate Content Security Policy headers", "text", "Enter allowed domains...", "Generate", "security"),
            ("cors-generator", "CORS Header Generator", "Generate Cross-Origin Resource Sharing headers", "text", "Enter allowed origins...", "Generate", "security"),
            ("markdown-link", "Markdown Link Generator", "Generate markdown links, images, and references", "text", "Enter URL...", "Generate", "link"),
            ("html-link-embed", "HTML Link Embed Generator", "Generate HTML anchor tags with attributes", "text", "Enter URL...", "Generate", "link"),
        ],
    },
    "design": {
        "name": "Design & Visual",
        "icon": "palette",
        "tools": [
            ("color-picker", "Color Picker", "Pick colors from a color wheel and get HEX, RGB, HSL values", "text", "Enter color...", "Pick", "palette"),
            ("color-mixer", "Color Mixer", "Mix two colors together and get the result in HEX, RGB, HSL", "text", "Enter two colors...", "Mix", "palette"),
            ("color-palette-gen", "Color Palette Generator", "Generate complementary, analogous, triadic, and split-complementary palettes", "text", "Enter base color (HEX)...", "Generate", "palette"),
            ("gradient-maker", "CSS Gradient Maker", "Create linear, radial, and conic gradients with live preview", "text", "Optional preset...", "Create", "gradient"),
            ("box-shadow-maker", "CSS Box Shadow Maker", "Create box shadows with multiple layers and spread", "text", "Optional preset...", "Create", "shadow"),
            ("text-shadow-maker", "CSS Text Shadow Maker", "Create text shadows with multiple layers", "text", "Optional preset...", "Create", "text_fields"),
            ("border-radius", "CSS Border Radius Generator", "Generate CSS border-radius values with visual preview", "text", "Optional preset...", "Generate", "rounded_corner"),
            ("transform-generator", "CSS Transform Generator", "Generate CSS 2D and 3D transform values", "text", "Describe transform...", "Generate", "transform"),
            ("transition-generator", "CSS Transition Generator", "Generate CSS transition properties", "text", "Describe transition...", "Generate", "animation"),
            ("flexbox-playground", "CSS Flexbox Generator", "Generate flexbox layout CSS", "text", "Describe layout...", "Generate", "view_agenda"),
            ("grid-generator", "CSS Grid Generator", "Generate CSS grid layouts", "text", "Describe grid...", "Generate", "grid_on"),
            ("clip-path-generator", "CSS Clip Path Generator", "Generate CSS clip-path polygon values", "text", "Describe shape...", "Generate", "crop"),
            ("animation-generator", "CSS Animation Generator", "Create CSS keyframe animations for common effects", "text", "Describe animation...", "Generate", "animation"),
            ("font-pairing", "Font Pairing Generator", "Suggest Google Fonts pairings for headings and body text", "text", "Optional style preference...", "Generate", "font_download"),
            ("aspect-ratio", "Aspect Ratio Calculator", "Calculate and find aspect ratios for images and videos", "text", "Enter dimensions...", "Calculate", "aspect_ratio"),
            ("image-dimensions", "Image Dimension Calculator", "Calculate image dimensions based on aspect ratio and target size", "text", "Enter original dimensions...", "Calculate", "aspect_ratio"),
            ("safe-colors", "Safe Web Colors", "View all web-safe colors with HEX and RGB values", "text", "Search color...", "View", "palette"),
            ("material-colors", "Material Design Colors", "View Material Design color palette with shades", "text", "Search color...", "View", "palette"),
            ("contrast-checker", "WCAG Contrast Checker", "Check color contrast ratio for accessibility compliance", "text", "Enter two colors...", "Check", "visibility"),
            ("icon-search", "Material Icon Search", "Search and find Material Design icons by name", "text", "Search icons...", "Search", "search"),
            ("svg-path-editor", "SVG Path Generator", "Generate SVG path data for common shapes", "text", "Describe shape...", "Generate", "draw"),
            ("png-compressor", "PNG Compressor", "Compress PNG images to reduce file size", "text", "Upload PNG...", "Compress", "compress"),
            ("svg-optimizer", "SVG Optimizer", "Optimize SVG files by removing unnecessary attributes", "text", "Paste SVG code...", "Optimize", "compress"),
            ("css-cleaner", "CSS Cleaner", "Remove unused CSS rules and properties", "text", "Paste CSS here...", "Clean", "auto_fix_high"),
            ("image-filter", "Image Filter Preview", "Preview CSS filter effects on uploaded images", "text", "Upload image...", "Filter", "filter"),
            ("image-to-ascii", "Image to ASCII Art", "Convert uploaded images to ASCII art text", "text", "Upload image...", "Convert", "text_fields"),
            ("ascii-art", "Text to ASCII Art", "Convert text to ASCII art using figlet/toilet fonts", "text", "Enter text...", "Generate", "text_fields"),
            ("text-art", "Text Art Generator", "Create text art banners and decorative text", "text", "Enter text...", "Generate", "text_fields"),
            ("color-blindness", "Color Blindness Simulator", "Simulate how colors appear to people with different types of color blindness", "text", "Enter color (HEX)...", "Simulate", "visibility"),
            ("image-metadata", "Image Metadata Viewer", "View EXIF and metadata information from uploaded images", "text", "Upload image...", "View", "info"),
            ("favicon-generator", "Favicon Generator", "Generate favicon from text initials or emoji", "text", "Enter initials or emoji...", "Generate", "icon"),
        ],
    },
    "developer": {
        "name": "Developer Tools",
        "icon": "developer_mode",
        "tools": [
            ("json-schema-gen", "JSON Schema Generator", "Generate JSON Schema from sample JSON data", "text", "Paste sample JSON...", "Generate", "code"),
            ("mock-data-gen", "Mock Data Generator", "Generate realistic mock data for testing (names, emails, addresses)", "text", "Enter field type and count...", "Generate", "dynamic_feed"),
            ("api-mock-gen", "API Mock Generator", "Generate mock API responses from JSON templates", "text", "Paste JSON response template...", "Generate", "api"),
            ("diff-viewer", "Text Diff Viewer", "Compare two texts and highlight differences", "text", "Paste text 1...", "Compare", "compare"),
            ("cron-builder", "Cron Expression Builder", "Build cron expressions with visual field selectors", "text", "Describe schedule...", "Build", "schedule"),
            ("jwt-builder", "JWT Token Builder", "Build JWT tokens with custom header and payload", "text", "Enter payload JSON...", "Build", "vpn_key"),
            ("color-to-tailwind", "Color to Tailwind Config", "Convert color values to Tailwind CSS configuration", "text", "Enter color values...", "Convert", "code"),
            ("html-to-jsx", "HTML to JSX Converter", "Convert HTML to React JSX syntax", "text", "Paste HTML here...", "Convert", "code"),
            ("jsx-to-html", "JSX to HTML Converter", "Convert React JSX to plain HTML", "text", "Paste JSX here...", "Convert", "code"),
            ("css-to-js", "CSS to JavaScript Object", "Convert CSS styles to JavaScript style objects", "text", "Paste CSS here...", "Convert", "code"),
            ("js-to-css", "JavaScript Object to CSS", "Convert JS style objects to CSS", "text", "Paste JS object...", "Convert", "code"),
            ("html-entity-list", "HTML Entity Reference", "View all HTML entities with codes, names, and characters", "text", "Search entity...", "View", "code"),
            ("ascii-table-full", "ASCII Table Reference", "Complete ASCII table with decimal, hex, octal, binary values", "text", "Search character...", "View", "table"),
            ("unicode-table", "Unicode Table Explorer", "Browse Unicode characters by category and block", "text", "Search character...", "View", "table"),
            ("regex-cheatsheet", "Regex Cheat Sheet", "Quick reference for regular expression syntax", "text", "Search pattern...", "View", "find_replace"),
            ("linux-cheatsheet", "Linux Commands Reference", "Quick reference for common Linux commands", "text", "Search command...", "View", "terminal"),
            ("git-cheatsheet", "Git Commands Reference", "Quick reference for Git commands and workflows", "text", "Search command...", "View", "code"),
            ("docker-cheatsheet", "Docker Commands Reference", "Quick reference for Docker commands and Dockerfile syntax", "text", "Search command...", "View", "code"),
            ("sql-cheatsheet", "SQL Cheat Sheet", "Quick reference for SQL commands, joins, and functions", "text", "Search query...", "View", "data_object"),
            ("python-cheatsheet", "Python Cheat Sheet", "Quick reference for Python syntax, built-ins, and common patterns", "text", "Search topic...", "View", "code"),
            ("javascript-cheatsheet", "JavaScript Cheat Sheet", "Quick reference for JavaScript syntax, ES6+ features", "text", "Search feature...", "View", "code"),
            ("react-cheatsheet", "React Cheat Sheet", "Quick reference for React hooks, components, and patterns", "text", "Search hook/pattern...", "View", "code"),
            ("css-flexbox-cheat", "CSS Flexbox Cheat Sheet", "Visual reference for Flexbox properties and values", "text", "Search property...", "View", "code"),
            ("css-grid-cheat", "CSS Grid Cheat Sheet", "Visual reference for CSS Grid properties and values", "text", "Search property...", "View", "code"),
            ("http-status", "HTTP Status Codes", "Reference for all HTTP status codes with descriptions", "text", "Search code...", "View", "http"),
            ("error-code-ref", "Error Code Reference", "Common error codes across programming languages", "text", "Search error...", "View", "error"),
            ("date-format-ref", "Date Format Reference", "strftime/strptime format patterns for various languages", "text", "Search format...", "View", "schedule"),
            ("timezone-list", "Timezone List", "Complete list of IANA timezones with UTC offsets", "text", "Search timezone...", "View", "public"),
            ("emoji-list", "Emoji Reference", "Complete emoji list grouped by category", "text", "Search emoji...", "View", "emoji_emotions"),
            ("markdown-cheatsheet", "Markdown Cheat Sheet", "Complete Markdown syntax reference with examples", "text", "Search syntax...", "View", "code"),
            ("w3c-validator", "W3C HTML Validator", "Validate HTML5 syntax and check for errors", "text", "Paste HTML here...", "Validate", "check_circle"),
        ],
    },
    "encoding": {
        "name": "Encoding & Crypto",
        "icon": "lock",
        "tools": [
            ("base64-tool", "Base64 Encoder/Decoder", "Encode and decode Base64 strings with UTF-8 support", "text", "Enter text or Base64...", "Convert", "lock"),
            ("url-encode-tool", "URL Encoding Tool", "Encode and decode URL components with proper escaping", "text", "Enter URL component...", "Convert", "link"),
            ("html-entity-tool", "HTML Entity Encoding", "Encode and decode HTML entities with named and numeric references", "text", "Enter text or entities...", "Convert", "code"),
            ("hex-encode-tool", "Hexadecimal Encoding", "Convert text to hex and hex to text", "text", "Enter text or hex string...", "Convert", "code"),
            ("binary-encode-tool", "Binary Encoding", "Convert text to binary and binary to text", "text", "Enter text or binary...", "Convert", "memory"),
            ("octal-encode-tool", "Octal Encoding", "Convert text to octal and octal to text", "text", "Enter text or octal...", "Convert", "code"),
            ("unicode-encode", "Unicode Encoding", "Convert text to Unicode escape sequences and back", "text", "Enter text or Unicode escapes...", "Convert", "translate"),
            ("punycode-tool", "Punycode Encoder/Decoder", "Encode and decode internationalized domain names", "text", "Enter domain name...", "Convert", "language"),
            ("morse-encoder", "Morse Code Encoder", "Convert text to International Morse Code", "text", "Enter text...", "Encode", "radio"),
            ("morse-decoder", "Morse Code Decoder", "Convert Morse Code back to text", "text", "Enter morse code...", "Decode", "radio"),
            ("pig-latin-tool", "Pig Latin Translator", "Convert English to Pig Latin and back", "text", "Enter text...", "Translate", "record_voice_over"),
            ("reverse-text-tool", "Text Reverser", "Reverse text, words, sentences, or characters", "text", "Enter text...", "Reverse", "flip"),
            ("bubble-text", "Bubble Text Generator", "Convert text to bubble ( SpongeBob style) text", "text", "Enter text...", "Convert", "text_fields"),
            ("fancy-text", "Fancy Text Generator", "Convert text to fancy Unicode styles ( Mathematical, Script, Fraktur)", "text", "Enter text...", "Generate", "text_fields"),
            ("cipher-wheel", "Cipher Wheel Tool", "Encode/decode using a Caesar cipher with customizable shift", "text", "Enter text...", "Process", "swap_horiz"),
            ("substitution-cipher", "Substitution Cipher Tool", "Encode/decode with a custom substitution alphabet", "text", "Enter text...", "Process", "lock"),
            ("transposition-cipher", "Transposition Cipher Tool", "Encode/decode with columnar transposition", "text", "Enter text...", "Process", "lock"),
            ("brute-force-decoder", "Caesar Cipher Brute Force", "Try all 25 Caesar cipher shifts to decode unknown text", "text", "Enter ciphertext...", "Decode", "lock"),
            ("hash-lookup", "Hash Lookup", "Look up known MD5/SHA hashes in common databases", "text", "Enter hash...", "Lookup", "search"),
            ("password-checker", "Password Quality Analyzer", "Analyze password patterns, entropy, and estimated crack time", "text", "Enter password...", "Analyze", "security"),
            ("passphrase-gen", "Passphrase Generator", "Generate memorable passphrases from word lists", "text", "Optional word count...", "Generate", "vpn_key"),
            ("random-bytes", "Random Bytes Generator", "Generate random bytes in various formats (hex, base64, binary)", "text", "Enter byte count...", "Generate", "casino"),
            ("encoding-detector", "Text Encoding Detector", "Detect character encoding of pasted text", "text", "Paste text to detect...", "Detect", "search"),
            ("utf8-validator", "UTF-8 Validator", "Validate if text is valid UTF-8 and show code points", "text", "Paste text...", "Validate", "check_circle"),
            ("idn-converter", "IDN Converter", "Convert internationalized domain names to Punycode and back", "text", "Enter domain...", "Convert", "language"),
            ("slash-escape", "String Escape Tool", "Escape/unescape strings for JavaScript, Python, JSON, and SQL", "text", "Enter string...", "Convert", "code"),
            ("character-map", "Extended ASCII Map", "View extended ASCII characters (128-255) with descriptions", "text", "Search character...", "View", "table"),
            ("base-n-converter", "Base-N Converter", "Convert numbers between base 2 through 36", "text", "Enter number and base...", "Convert", "swap_horiz"),
            ("encoding-chains", "Encoding Chain Tool", "Apply multiple encoding layers (Base64 + URL + HTML)", "text", "Enter text...", "Encode", "layers"),
        ],
    },
    "statistics": {
        "name": "Statistics & Analysis",
        "icon": "analytics",
        "tools": [
            ("mean-median-mode", "Mean, Median & Mode Calculator", "Calculate statistical mean, median, mode, and range", "text", "Enter numbers (comma-separated)...", "Calculate", "calculate"),
            ("standard-deviation", "Standard Deviation Calculator", "Calculate population and sample standard deviation", "text", "Enter numbers (comma-separated)...", "Calculate", "calculate"),
            ("z-score", "Z-Score Calculator", "Calculate Z-scores and find percentiles", "text", "Enter value, mean, and std dev...", "Calculate", "calculate"),
            ("correlation", "Correlation Coefficient Calculator", "Calculate Pearson correlation between two data sets", "text", "Enter two data sets...", "Calculate", "calculate"),
            ("linear-regression", "Linear Regression Calculator", "Calculate slope, intercept, and R² for linear regression", "text", "Enter X,Y data pairs...", "Calculate", "calculate"),
            ("probability", "Probability Calculator", "Calculate probability of events with combinations and permutations", "text", "Enter event counts...", "Calculate", "calculate"),
            ("combinatorics", "Combinations & Permutations", "Calculate nCr and nPr values", "text", "Enter n and r...", "Calculate", "calculate"),
            ("confidence-interval", "Confidence Interval Calculator", "Calculate confidence intervals for means", "text", "Enter sample data...", "Calculate", "calculate"),
            ("sample-size", "Sample Size Calculator", "Calculate required sample size for surveys", "text", "Enter margin of error and confidence level...", "Calculate", "calculate"),
            ("margin-of-error", "Margin of Error Calculator", "Calculate margin of error from sample size", "text", "Enter sample size and confidence level...", "Calculate", "calculate"),
            ("chi-square", "Chi-Square Calculator", "Calculate chi-square test statistic", "text", "Enter observed and expected frequencies...", "Calculate", "calculate"),
            ("t-test", "T-Test Calculator", "Perform one-sample and two-sample t-tests", "text", "Enter sample data...", "Calculate", "calculate"),
            ("anova", "ANOVA Calculator", "Perform one-way ANOVA test", "text", "Enter groups of data...", "Calculate", "calculate"),
            ("frequency-table", "Frequency Table Generator", "Generate frequency distributions from data sets", "text", "Enter data values...", "Generate", "table_chart"),
            ("histogram-data", "Histogram Data Generator", "Generate histogram bin counts from data sets", "text", "Enter data values...", "Generate", "bar_chart"),
            ("percentile", "Percentile Calculator", "Calculate percentiles and quartiles from data", "text", "Enter numbers (comma-separated)...", "Calculate", "calculate"),
            ("data-sorter", "Data Sorter", "Sort numerical data sets with statistics summary", "text", "Enter numbers (comma-separated)...", "Sort", "sort"),
            ("outlier-detector", "Outlier Detector", "Detect outliers in data sets using IQR method", "text", "Enter numbers (comma-separated)...", "Detect", "analytics"),
            ("average-calculator", "Average Calculator", "Calculate mean, median, mode, range, and variance", "text", "Enter numbers (comma-separated)...", "Calculate", "calculate"),
            ("weighted-average", "Weighted Average Calculator", "Calculate weighted averages with custom weights", "text", "Enter values and weights...", "Calculate", "calculate"),
            ("geometric-mean", "Geometric Mean Calculator", "Calculate geometric mean of positive numbers", "text", "Enter positive numbers...", "Calculate", "calculate"),
            ("harmonic-mean", "Harmonic Mean Calculator", "Calculate harmonic mean of positive numbers", "text", "Enter positive numbers...", "Calculate", "calculate"),
            ("moving-average", "Moving Average Calculator", "Calculate simple and exponential moving averages", "text", "Enter data points and window size...", "Calculate", "calculate"),
            ("data-visualization", "ASCII Chart Generator", "Generate ASCII bar charts and line charts from data", "text", "Enter data values...", "Generate", "bar_chart"),
            ("word-cloud-data", "Word Cloud Data Generator", "Generate word frequency data for word cloud visualization", "text", "Enter text to analyze...", "Generate", "cloud"),
        ],
    },
}


def create_tool(slug, name, description, input_type, placeholder, button_label, button_icon, category):
    """Create a tool directory with tool.json and handler.js."""
    tool_dir = os.path.join(TOOLS_DIR, slug)
    os.makedirs(tool_dir, exist_ok=True)

    # tool.json
    tool_data = {
        "slug": slug,
        "name": name,
        "icon": button_icon,
        "category": category,
        "description": description,
        "input_type": "url" if input_type == "url" else "text",
        "placeholder": placeholder,
        "button_label": button_label,
        "button_icon": button_icon,
    }

    # Add config from tool_configs
    config = TOOL_CONFIGS.get(slug, {})
    if config:
        tool_data["config"] = config

    with open(os.path.join(tool_dir, "tool.json"), "w", encoding="utf-8") as f:
        json.dump(tool_data, f, indent=4)

    # handler.js — minimal, delegates to processors.js via tool.js
    handler_content = f"""/**
 * {name} — handler.js
 * Delegates to Processors.{slug.replace('-', '_')}() in processors.js
 */
(function() {{
  // Register as a text-processing tool
  // tool.js will auto-invoke Processors.{slug.replace('-', '_')}()
}})();
"""
    with open(os.path.join(tool_dir, "handler.js"), "w", encoding="utf-8") as f:
        f.write(handler_content)


def main():
    """Generate all tool directories."""
    total = 0
    for category_key, category_data in CATEGORIES.items():
        cat_name = category_data["name"]
        tools = category_data["tools"]
        for tool_data in tools:
            slug, name, description, input_type, placeholder, button_label, button_icon = tool_data
            create_tool(slug, name, description, input_type, placeholder, button_label, button_icon, cat_name)
            total += 1

    print(f"Generated {total} tools across {len(CATEGORIES)} categories")


if __name__ == "__main__":
    main()
