#!/usr/bin/env python3
"""
Tool configurations — input fields and processor mappings.
Imported by generate_tools.py to add config to each tool.json.
"""

TOOL_CONFIGS = {
    # ─── TEXT TOOLS ───────────────────────────────────────────
    "case-converter": {
        "processor": "case_converter",
        "inputs": [{"name": "mode", "type": "select", "label": "Convert to:", "options": ["UPPERCASE", "lowercase", "Title Case", "Sentence case", "aLtErNaTiNg CaSe", "iNVERSE cAsE"], "default": "UPPERCASE"}],
    },
    "text-reverser": {"processor": "text_reverser"},
    "line-sorter": {"processor": "line_sorter"},
    "line-numberer": {"processor": "line_numberer"},
    "find-replace": {
        "processor": "find_replace",
        "inputs": [
            {"name": "find_text", "type": "text", "label": "Find:", "placeholder": "Text to find..."},
            {"name": "replace_text", "type": "text", "label": "Replace with:", "placeholder": "Replacement text..."},
            {"name": "use_regex", "type": "checkbox", "label": "Use Regex"},
            {"name": "case_insensitive", "type": "checkbox", "label": "Case Insensitive"},
        ],
    },
    "text-cleaner": {"processor": "text_cleaner"},
    "text-trimmer": {
        "processor": "text_trimmer",
        "inputs": [{"name": "char_limit", "type": "number", "label": "Max Characters:", "default": "100"}],
    },
    "text-duplicator": {
        "processor": "text_duplicator",
        "inputs": [
            {"name": "times", "type": "number", "label": "Repeat count:", "default": "3"},
            {"name": "separator", "type": "text", "label": "Separator:", "placeholder": "e.g. \\n---\\n"},
        ],
    },
    "word-frequency": {"processor": "word_frequency"},
    "text-diff": {
        "processor": "text_diff",
        "inputs": [{"name": "text2", "type": "textarea", "label": "Text 2:", "height": "100"}],
    },
    "text-summarizer": {"processor": "text_summary"},
    "markdown-preview": {"processor": "markdown_preview"},
    "text-encoder": {
        "processor": "text_encoder",
        "inputs": [{"name": "mode", "type": "select", "label": "Encoding:", "options": [{"value": "all", "label": "All"}, {"value": "base64", "label": "Base64"}, {"value": "url", "label": "URL Encoding"}, {"value": "html", "label": "HTML Entities"}, {"value": "rot13", "label": "ROT13"}]}],
    },
    "text-to-slugs": {"processor": "text_to_slugs"},
    "binary-text": {"processor": "binary_text"},
    "morse-code": {"processor": "morse_code"},
    "pig-latin": {"processor": "pig_latin"},
    "palindrome-checker": {"processor": "palindrome_checker"},
    "acronym-generator": {"processor": "acronym_generator"},
    "name-generator": {
        "processor": "name_generator",
        "inputs": [{"name": "count", "type": "number", "label": "Number of names:", "default": "5"}],
    },

    # ─── CODE TOOLS ───────────────────────────────────────────
    "json-formatter": {"processor": "json_formatter"},
    "json-validator": {"processor": "json_validator"},
    "json-minifier": {"processor": "json_minifier"},
    "json-to-csv": {"processor": "json_to_csv"},
    "csv-to-json": {"processor": "csv_to_json"},
    "xml-formatter": {"processor": "xml_formatter"},
    "xml-validator": {"processor": "xml_validator"},
    "xml-to-json": {"processor": "xml_to_json"},
    "json-to-xml": {"processor": "json_to_xml"},
    "yaml-formatter": {"processor": "yaml_formatter"},
    "html-formatter": {"processor": "html_formatter"},
    "html-minifier": {"processor": "html_minifier"},
    "css-formatter": {"processor": "css_formatter"},
    "css-minifier": {"processor": "css_minifier"},
    "js-formatter": {"processor": "js_formatter"},
    "js-minifier": {"processor": "js_minifier"},
    "js-beautifier": {"processor": "js_beautifier"},
    "sql-formatter": {"processor": "sql_formatter"},
    "sql-validator": {"processor": "sql_validator"},
    "sort-lines": {"processor": "sort_lines"},
    "deduplicate-lines": {"processor": "deduplicate_lines"},
    "base64-encode": {"processor": "base64_encode"},
    "url-encode": {"processor": "url_encode"},
    "html-entity-encode": {"processor": "html_entity_encode"},
    "jwt-decoder": {"processor": "jwt_decoder"},
    "color-converter": {"processor": "color_converter"},
    "regex-tester": {
        "processor": "regex_tester",
        "inputs": [{"name": "pattern", "type": "text", "label": "Regex Pattern:", "placeholder": "e.g. \\d+"}],
    },

    # ─── CRYPTO TOOLS ─────────────────────────────────────────
    "hash-generator": {
        "processor": "hash_generator",
        "inputs": [{"name": "algorithm", "type": "select", "label": "Algorithm:", "options": [{"value": "all", "label": "All Algorithms"}, {"value": "SHA-256", "label": "SHA-256"}, {"value": "SHA-512", "label": "SHA-512"}, {"value": "SHA-1", "label": "SHA-1"}, {"value": "CRC32", "label": "CRC32"}]}],
    },
    "md5-generator": {"processor": "md5_generator"},
    "sha1-generator": {"processor": "sha1_generator"},
    "sha256-generator": {"processor": "sha256_generator"},
    "sha512-generator": {"processor": "sha512_generator"},
    "hmac-generator": {"processor": "hmac_generator"},
    "caesar-cipher": {
        "processor": "caesar_cipher",
        "inputs": [{"name": "shift", "type": "number", "label": "Shift value:", "default": "3"}],
    },
    "rot13": {"processor": "rot13"},
    "password-strength": {"processor": "password_strength"},
    "binary-encoder": {"processor": "binary_encoder"},
    "hex-encoder": {"processor": "hex_encoder"},
    "unicode-converter": {"processor": "unicode_converter"},
    "token-generator": {
        "processor": "token_generator",
        "inputs": [{"name": "length", "type": "number", "label": "Token length:", "default": "32"}],
    },
    "atbash-cipher": {"processor": "rot13"},

    # ─── GENERATOR TOOLS ──────────────────────────────────────
    "password-generator": {
        "processor": "password_generator",
        "inputs": [
            {"name": "length", "type": "number", "label": "Password length:", "default": "16"},
            {"name": "uppercase", "type": "checkbox", "label": "Uppercase (A-Z)", "default": True},
            {"name": "lowercase", "type": "checkbox", "label": "Lowercase (a-z)", "default": True},
            {"name": "numbers", "type": "checkbox", "label": "Numbers (0-9)", "default": True},
            {"name": "symbols", "type": "checkbox", "label": "Symbols (!@#$...)", "default": True},
        ],
    },
    "random-password": {"processor": "password_generator"},
    "uuid-generator": {
        "processor": "uuid_generator",
        "inputs": [{"name": "count", "type": "number", "label": "Count:", "default": "5"}],
    },
    "uuid-v4": {"processor": "uuid_generator"},
    "random-number": {
        "processor": "random_number",
        "inputs": [
            {"name": "min", "type": "number", "label": "Min:", "default": "1"},
            {"name": "max", "type": "number", "label": "Max:", "default": "100"},
            {"name": "count", "type": "number", "label": "Count:", "default": "10"},
        ],
    },
    "random-string": {
        "processor": "random_string",
        "inputs": [{"name": "length", "type": "number", "label": "Length:", "default": "16"}],
    },
    "random-color": {"processor": "random_color"},
    "random-email": {"processor": "random_email"},
    "random-address": {"processor": "random_address"},
    "random-phone": {"processor": "random_phone"},
    "random-name": {"processor": "random_name"},
    "random-boolean": {"processor": "random_boolean"},
    "random-date": {"processor": "random_date"},
    "random-unit": {"processor": "random_unit"},
    "font-generator": {"processor": "font_generator"},
    "lorem-ipsum": {
        "processor": "lorem_ipsum",
        "inputs": [
            {"name": "count", "type": "number", "label": "Count:", "default": "3"},
            {"name": "type", "type": "select", "label": "Type:", "options": [{"value": "paragraphs", "label": "Paragraphs"}, {"value": "sentences", "label": "Sentences"}, {"value": "words", "label": "Words"}]},
        ],
    },
    "lorem-paragraphs": {"processor": "lorem_ipsum"},
    "lorem-words": {"processor": "lorem_ipsum"},
    "lorem-sentences": {"processor": "lorem_ipsum"},
    "qr-code": {"processor": "qr_code"},
    "barcode": {"processor": "barcode"},
    "placeholder-image": {
        "processor": "placeholder_image",
        "inputs": [{"name": "size", "type": "text", "label": "Dimensions:", "placeholder": "300x200", "default": "300x200"}],
    },
    "random-fortune": {
        "processor": "random_fortune",
        "inputs": [{"name": "type", "type": "select", "label": "Theme:", "options": ["motivational", "funny", "tech", "life"]}],
    },
    "dice-roller": {
        "processor": "dice_roller",
        "inputs": [{"name": "notation", "type": "text", "label": "Dice Notation:", "placeholder": "2d6+3", "default": "1d6"}],
    },
    "coin-flip": {
        "processor": "coin_flip",
        "inputs": [{"name": "count", "type": "number", "label": "Flips:", "default": "1"}],
    },

    # ─── CALCULATOR TOOLS ─────────────────────────────────────
    "scientific-calculator": {"processor": "scientific_calculator"},
    "percentage-calculator": {"processor": "percentage_calculator"},
    "tip-calculator": {"processor": "tip_calculator"},
    "unit-converter": {"processor": "unit_converter"},
    "temperature-converter": {"processor": "temperature_converter"},
    "speed-converter": {"processor": "speed_converter"},
    "data-converter": {"processor": "data_converter"},
    "time-converter": {"processor": "time_converter"},
    "number-base": {"processor": "number_base"},
    "scientific-notation": {"processor": "scientific_notation"},
    "roman-numeral": {"processor": "roman_numeral"},
    "quadratic-solver": {"processor": "quadratic_solver"},
    "age-calculator": {"processor": "age_calculator"},
    "bmi-calculator": {"processor": "bmi_calculator"},
    "calorie-calculator": {"processor": "calorie_calculator"},
    "date-calculator": {"processor": "date_calculator"},
    "days-between": {"processor": "days_between"},
    "timestamp-converter": {"processor": "timestamp_converter"},
    "factorial-calculator": {"processor": "probability"},
    "gcd-lcm": {"processor": "gcd_lcm"},
    "prime-checker": {"processor": "prime_checker"},
    "z-score": {"processor": "z_score"},

    # ─── STATISTICS TOOLS ─────────────────────────────────────
    "mean-median-mode": {"processor": "mean_median_mode"},
    "standard-deviation": {"processor": "standard_deviation"},
    "average-calculator": {"processor": "average_calculator"},
    "percentile": {"processor": "percentile"},
    "data-sorter": {"processor": "data_sorter"},
    "probability": {"processor": "probability"},
    "combinatorics": {"processor": "combinatorics"},
    "data-visualization": {"processor": "data_visualization"},
    "linear-regression": {"processor": "linear_regression"},
    "confidence-interval": {"processor": "confidence_interval"},
    "sample-size": {"processor": "sample_size"},
    "margin-of-error": {"processor": "margin_of_error"},
    "chi-square": {"processor": "chi_square"},
    "t-test": {"processor": "t_test"},
    "anova": {"processor": "anova"},
    "frequency-table": {"processor": "frequency_table"},
    "histogram-data": {"processor": "histogram_data"},
    "outlier-detector": {"processor": "outlier_detector"},
    "weighted-average": {"processor": "weighted_average"},
    "geometric-mean": {"processor": "geometric_mean"},
    "harmonic-mean": {"processor": "harmonic_mean"},
    "moving-average": {"processor": "moving_average"},
    "word-cloud-data": {"processor": "word_cloud_data"},

    # ─── WEB TOOLS ────────────────────────────────────────────
    "url-encoder-tool": {"processor": "url_encoder_tool"},
    "url-parser": {"processor": "url_parser"},
    "user-agent-parser": {"processor": "user_agent_parser"},
    "readability-score": {"processor": "readability_score"},

    # ─── PLACEHOLDER TOOLS (will show "not yet available") ────
    "json-to-yaml": {"processor": "json_to_yaml"},
    "yaml-to-json": {"processor": "yaml_to_json"},
    "json-to-toml": {"processor": "json_to_toml"},
    "toml-to-json": {"processor": "toml_to_json"},
    "json-to-typescript": {"processor": "json_to_typescript"},
    "json-to-python": {"processor": "json_to_python"},
    "json-to-go-struct": {"processor": "json_to_go_struct"},
    "json-to-sql": {"processor": "json_to_sql"},
    "csv-to-sql": {"processor": "csv_to_sql"},
    "xml-to-yaml": {"processor": "xml_to_yaml"},
    "yaml-to-xml": {"processor": "yaml_to_xml"},
    "regex-to-nfa": {"processor": "regex_to_nfa"},
    "cron-parser": {"processor": "cron_parser"},
    "timezone-converter": {"processor": "timezone_converter"},
    "emoji-to-text": {"processor": "emoji_to_text"},
    "number-to-words": {"processor": "number_to_words"},
    "words-to-number": {"processor": "words_to_number"},
    "roman-to-arabic": {"processor": "roman_to_arabic"},
    "arabic-to-roman": {"processor": "arabic_to_roman"},
    "color-to-css": {"processor": "color_to_css"},
    "css-to-text": {"processor": "css_to_text"},
    "image-to-base64": {"processor": "image_to_base64"},
    "text-to-image": {"processor": "text_to_image"},
    "font-converter": {"processor": "font_converter"},
    "svg-to-css": {"processor": "svg_to_css"},
    "json-to-env": {"processor": "json_to_env"},
    "env-to-json": {"processor": "env_to_json"},
    "sql-to-json": {"processor": "sql_to_json"},
    "graphql-to-rest": {"processor": "graphql_to_rest"},
    "meta-tag-generator": {"processor": "meta_tag_generator"},
    "open-graph-generator": {"processor": "open_graph_generator"},
    "twitter-card-generator": {"processor": "twitter_card_generator"},
    "robots-txt-generator": {"processor": "robots_txt_generator"},
    "sitemap-generator": {"processor": "sitemap_generator"},
    "structured-data": {"processor": "structured_data"},
    "html-encoder": {"processor": "html_encoder"},
    "css-selector": {"processor": "css_selector"},
    "htaccess-generator": {"processor": "htaccess_generator"},
    "ssl-checker": {"processor": "ssl_checker"},
    "dns-checker": {"processor": "dns_checker"},
    "whois-lookup": {"processor": "whois_lookup"},
    "ip-lookup": {"processor": "ip_lookup"},
    "viewport-resizer": {"processor": "viewport_resizer"},
    "cookie-parser": {"processor": "cookie_parser"},
    "http-header-viewer": {"processor": "http_header_viewer"},
    "json-ld-viewer": {"processor": "json_ld_viewer"},
    "redirect-checker": {"processor": "redirect_checker"},
    "page-size-checker": {"processor": "page_size_checker"},
    "word-count-seo": {"processor": "word_count_seo"},
    "json-sitemap": {"processor": "json_sitemap"},
    "base64-url-embed": {"processor": "base64_url_embed"},
    "csp-generator": {"processor": "csp_generator"},
    "cors-generator": {"processor": "cors_generator"},
    "markdown-link": {"processor": "markdown_link"},
    "html-link-embed": {"processor": "html_link_embed"},
    "color-picker": {"processor": "color_picker"},
    "color-mixer": {"processor": "color_mixer"},
    "color-palette-gen": {"processor": "color_palette_gen"},
    "gradient-maker": {"processor": "gradient_maker"},
    "box-shadow-maker": {"processor": "box_shadow_maker"},
    "text-shadow-maker": {"processor": "text_shadow_maker"},
    "border-radius": {"processor": "border_radius"},
    "transform-generator": {"processor": "transform_generator"},
    "transition-generator": {"processor": "transition_generator"},
    "flexbox-playground": {"processor": "flexbox_playground"},
    "grid-generator": {"processor": "grid_generator"},
    "clip-path-generator": {"processor": "clip_path_generator"},
    "animation-generator": {"processor": "animation_generator"},
    "font-pairing": {"processor": "font_pairing"},
    "aspect-ratio": {"processor": "aspect_ratio"},
    "image-dimensions": {"processor": "image_dimensions"},
    "safe-colors": {"processor": "safe_colors"},
    "material-colors": {"processor": "material_colors"},
    "contrast-checker": {"processor": "contrast_checker"},
    "icon-search": {"processor": "icon_search"},
    "svg-path-editor": {"processor": "svg_path_editor"},
    "png-compressor": {"processor": "png_compressor"},
    "svg-optimizer": {"processor": "svg_optimizer"},
    "css-cleaner": {"processor": "css_cleaner"},
    "image-filter": {"processor": "image_filter"},
    "image-to-ascii": {"processor": "image_to_ascii"},
    "ascii-art": {"processor": "ascii_art"},
    "text-art": {"processor": "text_art"},
    "color-blindness": {"processor": "color_blindness"},
    "image-metadata": {"processor": "image_metadata"},
    "favicon-generator": {"processor": "favicon_generator"},
    "json-schema-gen": {"processor": "json_schema_gen"},
    "mock-data-gen": {"processor": "mock_data_gen"},
    "api-mock-gen": {"processor": "api_mock_gen"},
    "diff-viewer": {"processor": "diff_viewer"},
    "cron-builder": {"processor": "cron_builder"},
    "jwt-builder": {"processor": "jwt_builder"},
    "color-to-tailwind": {"processor": "color_to_tailwind"},
    "html-to-jsx": {"processor": "html_to_jsx"},
    "jsx-to-html": {"processor": "jsx_to_html"},
    "css-to-js": {"processor": "css_to_js"},
    "js-to-css": {"processor": "js_to_css"},
    "html-entity-list": {"processor": "html_entity_list"},
    "ascii-table-full": {"processor": "ascii_table_full"},
    "unicode-table": {"processor": "unicode_table"},
    "regex-cheatsheet": {"processor": "regex_cheatsheet"},
    "linux-cheatsheet": {"processor": "linux_cheatsheet"},
    "git-cheatsheet": {"processor": "git_cheatsheet"},
    "docker-cheatsheet": {"processor": "docker_cheatsheet"},
    "sql-cheatsheet": {"processor": "sql_cheatsheet"},
    "python-cheatsheet": {"processor": "python_cheatsheet"},
    "javascript-cheatsheet": {"processor": "javascript_cheatsheet"},
    "react-cheatsheet": {"processor": "react_cheatsheet"},
    "css-flexbox-cheat": {"processor": "css_flexbox_cheat"},
    "css-grid-cheat": {"processor": "css_grid_cheat"},
    "http-status": {"processor": "http_status"},
    "error-code-ref": {"processor": "error_code_ref"},
    "date-format-ref": {"processor": "date_format_ref"},
    "timezone-list": {"processor": "timezone_list"},
    "emoji-list": {"processor": "emoji_list"},
    "markdown-cheatsheet": {"processor": "markdown_cheatsheet"},
    "w3c-validator": {"processor": "w3c_validator"},
    "base64-tool": {"processor": "base64_tool"},
    "url-encode-tool": {"processor": "url_encode_tool"},
    "html-entity-tool": {"processor": "html_entity_tool"},
    "hex-encode-tool": {"processor": "hex_encode_tool"},
    "binary-encode-tool": {"processor": "binary_encode_tool"},
    "octal-encode-tool": {"processor": "octal_encode_tool"},
    "unicode-encode": {"processor": "unicode_encode"},
    "punycode-tool": {"processor": "punycode_tool"},
    "morse-encoder": {"processor": "morse_encoder"},
    "morse-decoder": {"processor": "morse_decoder"},
    "pig-latin-tool": {"processor": "pig_latin_tool"},
    "reverse-text-tool": {"processor": "reverse_text_tool"},
    "bubble-text": {"processor": "bubble_text"},
    "fancy-text": {"processor": "fancy_text"},
    "cipher-wheel": {"processor": "cipher_wheel"},
    "substitution-cipher": {"processor": "substitution_cipher"},
    "transposition-cipher": {"processor": "transposition_cipher"},
    "brute-force-decoder": {"processor": "brute_force_decoder"},
    "hash-lookup": {"processor": "hash_lookup"},
    "password-checker": {"processor": "password_checker"},
    "passphrase-gen": {"processor": "passphrase_gen"},
    "random-bytes": {"processor": "random_bytes"},
    "encoding-detector": {"processor": "encoding_detector"},
    "utf8-validator": {"processor": "utf8_validator"},
    "idn-converter": {"processor": "idn_converter"},
    "slash-escape": {"processor": "slash_escape"},
    "character-map": {"processor": "character_map"},
    "base-n-converter": {"processor": "base_n_converter"},
    "encoding-chains": {"processor": "encoding_chains"},
    "css-to-scss": {"processor": "css_to_scss"},
    "python-formatter": {"processor": "python_formatter"},
    "code-beautifier": {"processor": "code_beautifier"},
    "code-minifier": {"processor": "code_minifier"},
    "code-obfuscator": {"processor": "code_obfuscator"},
    "code-documenter": {"processor": "code_documenter"},
    "text-cleaner": {"processor": "text_cleaner"},
    "word-counter": {"processor": "word_counter"},
    "char-counter": {"processor": "char_counter"},
    "sentence-counter": {"processor": "sentence_counter"},
    "paragraph-counter": {"processor": "paragraph_counter"},
    "reading-time": {"processor": "reading_time"},
    "text-stats": {"processor": "text_stats"},
    "lorem-generator": {"processor": "lorem_ipsum"},
    "name-generator-alt": {"processor": "name_generator"},
    "emoji-picker": {"processor": "emoji_picker"},
    "sentence-counter": {"processor": "sentence_counter"},
}
