#!/usr/bin/env python3
"""Update all tool.json with examples, placeholders, and proper input configs."""
import json, os

TOOLS_DIR = "tools"

# slug -> config overrides
UPDATES = {
    # ─── TEXT TOOLS ───────────────────────────────────────────
    "word-counter": {"placeholder": "Paste your text here to count words, characters, sentences...", "example": "The quick brown fox jumps over the lazy dog."},
    "char-counter": {"placeholder": "Paste text to count characters with/without spaces...", "example": "Hello World! This is a test."},
    "sentence-counter": {"placeholder": "Paste text to count sentences and words per sentence...", "example": "Hello world. How are you? I am fine."},
    "paragraph-counter": {"placeholder": "Paste text to count paragraphs and lines...", "example": "First paragraph here.\n\nSecond paragraph here."},
    "reading-time": {"placeholder": "Paste text to estimate reading and speech time...", "example": "This is a sample article about technology and its impact on modern society."},
    "case-converter": {"placeholder": "Paste text to convert case...", "example": "hello world example text"},
    "text-reverser": {"placeholder": "Paste text to reverse characters, words, or lines...", "example": "Hello World"},
    "text-duplicator": {"placeholder": "Paste text to duplicate multiple times...", "example": "Line to repeat"},
    "line-sorter": {"placeholder": "Paste lines to sort alphabetically, by length, or remove duplicates...", "example": "banana\napple\ncherry\ndate"},
    "line-numberer": {"placeholder": "Paste text to add line numbers...", "example": "First line\nSecond line\nThird line"},
    "find-replace": {"placeholder": "Paste text containing what you want to find...", "example": "Hello World, Hello Universe, Hello Friends"},
    "text-cleaner": {"placeholder": "Paste messy text to clean up extra spaces and blank lines...", "example": "Hello   World  \n\n\n  Extra   spaces   here"},
    "text-trimmer": {"placeholder": "Paste text to trim to a character limit...", "example": "This is a long text that needs to be trimmed to a specific length."},
    "word-frequency": {"placeholder": "Paste text to analyze word frequency and most common words...", "example": "the cat sat on the mat the cat liked the mat"},
    "text-diff": {"placeholder": "Paste first text to compare...", "example": "Hello World\nThis is line two"},
    "text-summarizer": {"placeholder": "Paste a long article to extract key sentences...", "example": "Technology has changed the way we live. From smartphones to AI, innovation continues. Many industries have been transformed by digital tools."},
    "markdown-preview": {"placeholder": "Write Markdown to see live preview...", "example": "# Hello World\n\nThis is **bold** and *italic*.\n\n- Item 1\n- Item 2"},
    "text-encoder": {"placeholder": "Paste text to encode/decode with Base64, URL, ROT13...", "example": "Hello World! 你好世界"},
    "text-to-slugs": {"placeholder": "Enter a title or heading to convert to URL slug...", "example": "My Awesome Blog Post Title"},
    "binary-text": {"placeholder": "Enter text or binary to convert...", "example": "Hello"},
    "morse-code": {"placeholder": "Enter text or Morse code to convert...", "example": "SOS"},
    "pig-latin": {"placeholder": "Enter English text to translate to Pig Latin...", "example": "hello world"},
    "palindrome-checker": {"placeholder": "Enter text to check if it's a palindrome...", "example": "racecar"},
    "acronym-generator": {"placeholder": "Enter a phrase to generate an acronym from...", "example": "National Aeronautics and Space Administration"},
    "name-generator": {"placeholder": "Optional seed or prefix...", "example": ""},

    # ─── CODE TOOLS ───────────────────────────────────────────
    "json-formatter": {"placeholder": 'Paste JSON to format and beautify...\nExample: {"name":"John","age":30,"city":"NYC"}', "example": '{"name":"John","age":30,"hobbies":["reading","gaming"]}'},
    "json-validator": {"placeholder": "Paste JSON to validate and check for syntax errors...", "example": '{"valid": true, "number": 42}'},
    "json-minifier": {"placeholder": "Paste JSON to minify by removing whitespace...", "example": '{"name": "John", "age": 30}'},
    "json-to-csv": {"placeholder": "Paste JSON array to convert to CSV...\nExample: [{\"name\":\"John\",\"age\":30},{\"name\":\"Jane\",\"age\":25}]", "example": '[{"name":"John","age":30},{"name":"Jane","age":25}]'},
    "csv-to-json": {"placeholder": "Paste CSV data with headers to convert to JSON...\nExample: name,age\nJohn,30\nJane,25", "example": "name,age,city\nJohn,30,NYC\nJane,25,LA"},
    "xml-formatter": {"placeholder": "Paste XML to format with proper indentation...", "example": '<root><name>John</name><age>30</age></root>'},
    "xml-validator": {"placeholder": "Paste XML to validate syntax...", "example": '<root><item>Hello</item></root>'},
    "xml-to-json": {"placeholder": "Paste XML to convert to JSON...", "example": '<person><name>John</name><age>30</age></person>'},
    "json-to-xml": {"placeholder": "Paste JSON to convert to XML...", "example": '{"person":{"name":"John","age":30}}'},
    "yaml-formatter": {"placeholder": "Paste YAML to format and validate...", "example": "name: John\nage: 30\ncity: NYC"},
    "html-formatter": {"placeholder": "Paste HTML to format with proper indentation...", "example": '<div><p>Hello</p><ul><li>Item 1</li></ul></div>'},
    "html-minifier": {"placeholder": "Paste HTML to minify...", "example": '<div class="container">  <p>Hello World</p></div>'},
    "css-formatter": {"placeholder": "Paste CSS to format...", "example": ".container{margin:0;padding:10px}.text{color:red;font-size:14px}"},
    "css-minifier": {"placeholder": "Paste CSS to minify...", "example": ".container { margin: 0; padding: 10px; }"},
    "js-formatter": {"placeholder": "Paste JavaScript to format...", "example": 'function hello(){console.log("world");return true}'},
    "js-minifier": {"placeholder": "Paste JavaScript to minify...", "example": 'function hello() { console.log("world"); return true; }'},
    "js-beautifier": {"placeholder": "Paste obfuscated or minified JavaScript to beautify...", "example": 'var a=1;function b(){return a+2}'},
    "sql-formatter": {"placeholder": "Paste SQL query to format with proper indentation...", "example": "SELECT name, age FROM users WHERE age > 18 ORDER BY name"},
    "sql-validator": {"placeholder": "Paste SQL to validate syntax...", "example": "SELECT * FROM users WHERE id = 1"},
    "python-formatter": {"placeholder": "Paste Python code to format...", "example": "def hello():\n    x=1\n    if x>0:\n        print('positive')"},
    "sort-lines": {"placeholder": "Paste lines to sort alphabetically, by length, or numerically...", "example": "cherry\napple\ndate\nbanana"},
    "deduplicate-lines": {"placeholder": "Paste text to remove duplicate lines...", "example": "apple\nbanana\napple\ncherry\nbanana"},
    "base64-encode": {"placeholder": "Enter text to encode or Base64 string to decode...", "example": "Hello World!"},
    "url-encode": {"placeholder": "Enter URL or text to encode/decode...", "example": "https://example.com/path?key=hello world"},
    "html-entity-encode": {"placeholder": "Enter text with special characters to encode/decode...", "example": "Tom & Jerry <3"},
    "jwt-decoder": {"placeholder": "Paste JWT token to decode header, payload, and signature...", "example": "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoiSm9obiJ9.signature"},
    "color-converter": {"placeholder": "Enter color as HEX, RGB, or HSL to convert...\nExamples: #FF5733, rgb(255,87,51), hsl(14,100%,60%)", "example": "#FF5733"},
    "regex-tester": {"placeholder": "Enter regex pattern to test...\nExample: \\d+ for numbers", "example": "\\d+"},

    # ─── CRYPTO TOOLS ─────────────────────────────────────────
    "hash-generator": {"placeholder": "Enter text to hash with MD5, SHA-1, SHA-256, SHA-512...", "example": "Hello World"},
    "md5-generator": {"placeholder": "Enter text to generate MD5 hash...", "example": "Hello World"},
    "sha1-generator": {"placeholder": "Enter text to generate SHA-1 hash...", "example": "Hello World"},
    "sha256-generator": {"placeholder": "Enter text to generate SHA-256 hash...", "example": "Hello World"},
    "sha512-generator": {"placeholder": "Enter text to generate SHA-512 hash...", "example": "Hello World"},
    "hmac-generator": {"placeholder": "Enter message to generate HMAC...", "example": "secret message"},
    "caesar-cipher": {"placeholder": "Enter text to encrypt/decrypt with Caesar cipher...", "example": "Hello World"},
    "rot13": {"placeholder": "Enter text to encode/decode with ROT13...", "example": "Hello World"},
    "atbash-cipher": {"placeholder": "Enter text to encode/decode with Atbash cipher...", "example": "Hello World"},
    "password-strength": {"placeholder": "Enter password to check strength and entropy...", "example": "MyP@ssw0rd123!"},
    "binary-encoder": {"placeholder": "Enter text or binary to convert...", "example": "Hello"},
    "hex-encoder": {"placeholder": "Enter text or hex string to convert...", "example": "Hello World"},
    "unicode-converter": {"placeholder": "Enter text or Unicode code points to convert...", "example": "Hello 你好"},
    "token-generator": {"placeholder": "Optional prefix for token...", "example": ""},
    "brainfuck": {"placeholder": "Enter Brainfuck code to execute...", "example": "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++."},

    # ─── GENERATOR TOOLS ──────────────────────────────────────
    "password-generator": {"placeholder": "Optional notes or requirements...", "example": ""},
    "random-password": {"placeholder": "Optional notes...", "example": ""},
    "uuid-generator": {"placeholder": "Optional count...", "example": ""},
    "uuid-v4": {"placeholder": "Optional count...", "example": ""},
    "random-number": {"placeholder": "Optional min-max range...", "example": ""},
    "random-string": {"placeholder": "Optional length...", "example": ""},
    "random-color": {"placeholder": "Optional seed...", "example": ""},
    "random-email": {"placeholder": "Optional domain...", "example": ""},
    "random-address": {"placeholder": "Optional country...", "example": ""},
    "random-phone": {"placeholder": "Optional country code...", "example": ""},
    "random-name": {"placeholder": "Optional count or prefix...", "example": ""},
    "random-boolean": {"placeholder": "Optional count...", "example": ""},
    "random-date": {"placeholder": "Optional range (YYYY-MM-DD)...", "example": ""},
    "random-unit": {"placeholder": "Optional unit type...", "example": ""},
    "font-generator": {"placeholder": "Enter text to stylize with Unicode fonts...", "example": "Hello World"},
    "lorem-ipsum": {"placeholder": "Number of paragraphs...", "example": ""},
    "lorem-paragraphs": {"placeholder": "Number of paragraphs...", "example": ""},
    "lorem-words": {"placeholder": "Number of words...", "example": ""},
    "lorem-sentences": {"placeholder": "Number of sentences...", "example": ""},
    "qr-code": {"placeholder": "Enter text, URL, email, or WiFi credentials for QR code...", "example": "https://example.com"},
    "barcode": {"placeholder": "Enter data to encode as barcode...", "example": "1234567890"},
    "placeholder-image": {"placeholder": "Enter dimensions (e.g. 300x200)...", "example": "400x300"},
    "random-fortune": {"placeholder": "Optional theme (motivational, funny, tech, life)...", "example": ""},
    "dice-roller": {"placeholder": "Enter dice notation (e.g. 2d6+3)...", "example": "2d6"},
    "coin-flip": {"placeholder": "Optional number of flips...", "example": ""},
    "cuid-generator": {"placeholder": "Optional count...", "example": ""},
    "nanoid-generator": {"placeholder": "Optional length...", "example": ""},
    "sequential-id": {"placeholder": "Enter prefix (e.g. user, order)...", "example": "order"},
    "micro-uuid": {"placeholder": "Optional length...", "example": ""},
    "password-memorable": {"placeholder": "Optional word count...", "example": ""},
    "fake-user": {"placeholder": "Optional count...", "example": ""},
    "fake-product": {"placeholder": "Optional count...", "example": ""},
    "fake-company": {"placeholder": "Optional count...", "example": ""},
    "emoji-picker": {"placeholder": "Enter keyword to find emojis (e.g. heart, food, nature)...", "example": "heart"},
    "name-generator-alt": {"placeholder": "Optional prefix or seed...", "example": ""},
    "acronym-generator": {"placeholder": "Enter a phrase to abbreviate...", "example": "Application Programming Interface"},

    # ─── CALCULATOR TOOLS ─────────────────────────────────────
    "scientific-calculator": {"placeholder": "Enter math expression (e.g. sin(45) + log(100), sqrt(144), 2^10)...", "example": "sin(45) + sqrt(144)"},
    "percentage-calculator": {"placeholder": "Enter problem (e.g. 25% of 200, increase from 100 to 150)...", "example": "25% of 200"},
    "tip-calculator": {"placeholder": "Enter bill amount (e.g. 85.50)...", "example": "85.50"},
    "loan-calculator": {"placeholder": "Enter amount, interest rate %, and years (e.g. 25000, 5.5, 30)...", "example": "25000, 5.5, 30"},
    "mortgage-calculator": {"placeholder": "Enter home price, rate %, and years (e.g. 350000, 6.5, 30)...", "example": "350000, 6.5, 30"},
    "compound-interest": {"placeholder": "Enter principal, rate %, and years (e.g. 10000, 5, 10)...", "example": "10000, 5, 10"},
    "bmi-calculator": {"placeholder": "Enter weight in kg and height in cm (e.g. 70, 175)...", "example": "70, 175"},
    "calorie-calculator": {"placeholder": "Enter weight(kg), height(cm), age (e.g. 70, 175, 30)...", "example": "70, 175, 30"},
    "age-calculator": {"placeholder": "Enter birth date (YYYY-MM-DD)...", "example": "1990-05-15"},
    "date-calculator": {"placeholder": "Enter date and days to add/subtract (e.g. 2024-01-15 +30)...", "example": "2024-01-15 +30"},
    "days-between": {"placeholder": "Enter two dates (e.g. 2024-01-01 2024-12-31)...", "example": "2024-01-01, 2024-12-31"},
    "area-calculator": {"placeholder": "Enter dimensions (e.g. circle radius=5, rectangle 10x20)...", "example": "10, 20"},
    "volume-calculator": {"placeholder": "Enter dimensions (e.g. sphere radius=5, cylinder r=3 h=10)...", "example": "3, 10"},
    "pythagorean": {"placeholder": "Enter two sides of right triangle (e.g. 3, 4)...", "example": "3, 4"},
    "quadratic-solver": {"placeholder": "Enter coefficients a, b, c (e.g. 1, -5, 6)...", "example": "1, -5, 6"},
    "linear-solver": {"placeholder": "Enter equation (e.g. 2x + 3 = 7)...", "example": "2x + 3 = 7"},
    "unit-converter": {"placeholder": "Enter value and units (e.g. 100 kg to lbs, 100 C to F)...", "example": "100 kg to lbs"},
    "temperature-converter": {"placeholder": "Enter temperature (e.g. 100 C to F, 72 F to C)...", "example": "100 C to F"},
    "currency-converter": {"placeholder": "Enter amount and currencies (e.g. 100 USD to EUR)...", "example": "100 USD to EUR"},
    "speed-converter": {"placeholder": "Enter speed and units (e.g. 100 km/h to mph)...", "example": "100 km/h to mph"},
    "data-converter": {"placeholder": "Enter data size (e.g. 1024 KB to MB, 1 GB to MB)...", "example": "1024 KB to MB"},
    "time-converter": {"placeholder": "Enter time value (e.g. 3600 seconds to hours)...", "example": "3600 seconds to hours"},
    "number-base": {"placeholder": "Enter number to convert between binary, octal, decimal, hex...", "example": "255"},
    "scientific-notation": {"placeholder": "Enter number (e.g. 1230000 or 1.23e6)...", "example": "1230000"},
    "roman-numeral": {"placeholder": "Enter number (1-3999) or Roman numeral...", "example": "42"},
    "factorial-calculator": {"placeholder": "Enter a number (e.g. 10)...", "example": "10"},
    "fibonacci": {"placeholder": "Enter number of terms to generate...", "example": "10"},
    "prime-checker": {"placeholder": "Enter a number to check if prime...", "example": "17"},
    "gcd-lcm": {"placeholder": "Enter two numbers (e.g. 12, 18)...", "example": "12, 18"},
    "hex-calculator": {"placeholder": "Enter hex expression (e.g. FF + 1, A * B)...", "example": "FF + 1"},
    "binary-calculator": {"placeholder": "Enter binary expression (e.g. 1010 + 1100)...", "example": "1010 + 1100"},
    "electricity-calculator": {"placeholder": "Enter wattage and hours per day (e.g. 100, 8)...", "example": "100, 8"},

    # ─── STATISTICS TOOLS ─────────────────────────────────────
    "mean-median-mode": {"placeholder": "Enter numbers separated by commas (e.g. 1, 2, 3, 4, 5)...", "example": "1, 2, 3, 4, 5, 5, 8"},
    "standard-deviation": {"placeholder": "Enter numbers separated by commas...", "example": "2, 4, 4, 4, 5, 5, 7, 9"},
    "average-calculator": {"placeholder": "Enter numbers separated by commas...", "example": "10, 20, 30, 40, 50"},
    "percentile": {"placeholder": "Enter numbers separated by commas...", "example": "1, 2, 3, 4, 5, 6, 7, 8, 9, 10"},
    "data-sorter": {"placeholder": "Enter numbers separated by commas...", "example": "5, 3, 8, 1, 9, 2"},
    "probability": {"placeholder": "Enter n and r values for permutations/combinations (e.g. 10, 3)...", "example": "10, 3"},
    "combinatorics": {"placeholder": "Enter n and r values (e.g. 10, 3)...", "example": "10, 3"},
    "data-visualization": {"placeholder": "Enter numbers to generate ASCII bar chart...", "example": "10, 25, 15, 30, 20"},
    "z-score": {"placeholder": "Enter value, mean, and standard deviation (e.g. 85, 70, 10)...", "example": "85, 70, 10"},
    "linear-regression": {"placeholder": "Enter x,y data pairs (e.g. 1,2 3,4 5,6 7,8)...", "example": "1,2 3,4 5,6 7,8"},
    "confidence-interval": {"placeholder": "Enter sample values separated by commas...", "example": "23, 25, 28, 22, 27"},
    "sample-size": {"placeholder": "Enter margin of error and confidence level (e.g. 0.05, 95)...", "example": "0.05, 95"},
    "margin-of-error": {"placeholder": "Enter sample size and optional confidence level (e.g. 100, 95)...", "example": "100, 95"},
    "chi-square": {"placeholder": "Enter observed and expected frequencies (e.g. 50,45 30,35)...", "example": "50,45 30,35 20,20"},
    "t-test": {"placeholder": "Enter two groups separated by semicolon (e.g. 5,6,7; 8,9,10)...", "example": "5,6,7; 8,9,10"},
    "anova": {"placeholder": "Enter groups separated by semicolons (e.g. 1,2,3; 4,5,6; 7,8,9)...", "example": "1,2,3; 4,5,6; 7,8,9"},
    "frequency-table": {"placeholder": "Enter data values separated by commas...", "example": "1, 2, 2, 3, 3, 3, 4, 4, 4, 4"},
    "histogram-data": {"placeholder": "Enter data values separated by commas...", "example": "10, 20, 15, 25, 30, 15, 20"},
    "outlier-detector": {"placeholder": "Enter numbers separated by commas...", "example": "10, 12, 14, 15, 100, 13, 11"},
    "weighted-average": {"placeholder": "Enter values and weights (e.g. 80,0.3 90,0.5 70,0.2)...", "example": "80,0.3 90,0.5 70,0.2"},
    "geometric-mean": {"placeholder": "Enter positive numbers separated by commas...", "example": "2, 4, 8"},
    "harmonic-mean": {"placeholder": "Enter positive numbers separated by commas...", "example": "2, 4, 8"},
    "moving-average": {"placeholder": "Enter data points and optional window size (e.g. 10,20,15,25,30 window=3)...", "example": "10,20,15,25,30 window=3"},
    "word-cloud-data": {"placeholder": "Enter text to analyze word frequencies for word cloud...", "example": "technology innovation digital transformation future AI"},

    # ─── WEB TOOLS ────────────────────────────────────────────
    "url-encoder-tool": {"placeholder": "Enter URL or text to encode/decode...", "example": "https://example.com/path?key=hello world"},
    "url-parser": {"placeholder": "Enter URL to parse into components...", "example": "https://www.example.com:8080/path?q=search#section"},
    "url-builder": {"placeholder": "Enter base URL to analyze components...", "example": "https://api.example.com/v2/users?page=1"},
    "query-string": {"placeholder": "Enter query parameters (e.g. name=John&age=30)...", "example": "name=John&age=30&city=NYC"},
    "meta-tag-generator": {"placeholder": "Enter page title to generate meta tags...", "example": "My Website - Best Tools Online"},
    "open-graph-generator": {"placeholder": "Enter page title for Open Graph tags...", "example": "My Awesome Article"},
    "twitter-card-generator": {"placeholder": "Enter tweet content for Twitter Card tags...", "example": "Check out this amazing tool!"},
    "robots-txt-generator": {"placeholder": "Enter sitemap URL...", "example": "https://mysite.com/sitemap.xml"},
    "sitemap-generator": {"placeholder": "Enter URLs to include (one per line)...", "example": "https://example.com/\nhttps://example.com/about\nhttps://example.com/contact"},
    "structured-data": {"placeholder": "Enter entity type (Article, Product, Organization, Person, FAQ)...", "example": "Article"},
    "html-encoder": {"placeholder": "Enter HTML to encode/decode entities...", "example": "<div>Hello & Welcome</div>"},
    "css-selector": {"placeholder": "Describe the element (e.g. nav, .button, #header)...", "example": "nav > ul > li.active"},
    "htaccess-generator": {"placeholder": "Enter redirect path...", "example": "old-page"},
    "ssl-checker": {"placeholder": "Enter domain name to check...", "example": "example.com"},
    "dns-checker": {"placeholder": "Enter domain to look up DNS records...", "example": "example.com"},
    "whois-lookup": {"placeholder": "Enter domain for WHOIS lookup...", "example": "example.com"},
    "ip-lookup": {"placeholder": "Enter IP address for geolocation...", "example": "8.8.8.8"},
    "user-agent-parser": {"placeholder": "Paste user agent string to parse...", "example": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0 Safari/537.36"},
    "viewport-resizer": {"placeholder": "Enter screen width in pixels...", "example": "375"},
    "cookie-parser": {"placeholder": "Paste cookie header string to parse...", "example": "session=abc123; theme=dark; lang=en"},
    "http-header-viewer": {"placeholder": "Paste HTTP headers to parse...", "example": "Content-Type: application/json\nCache-Control: no-cache"},
    "json-ld-viewer": {"placeholder": "Paste JSON-LD structured data to validate...", "example": '{"@type":"WebSite","name":"My Site"}'},
    "redirect-checker": {"placeholder": "Enter URL to check redirects...", "example": "https://example.com/old-page"},
    "page-size-checker": {"placeholder": "Paste HTML to calculate page size...", "example": "<html><body><h1>Hello</h1></body></html>"},
    "word-count-seo": {"placeholder": "Paste article content for SEO word count...", "example": "Technology is transforming how we work and live in the modern world."},
    "readability-score": {"placeholder": "Paste text to analyze readability (Flesch, Gunning Fog)...", "example": "The quick brown fox jumps over the lazy dog. This is a simple sentence."},
    "json-sitemap": {"placeholder": "Enter URLs (one per line) for sitemap...", "example": "https://example.com/\nhttps://example.com/about"},
    "base64-url-embed": {"placeholder": "Enter text to embed as data URI...", "example": "Hello World"},
    "csp-generator": {"placeholder": "Enter allowed domains for Content Security Policy...", "example": "https://cdn.example.com https://fonts.googleapis.com"},
    "cors-generator": {"placeholder": "Enter allowed origins for CORS headers...", "example": "https://mysite.com"},
    "markdown-link": {"placeholder": "Enter URL to generate markdown link/image...", "example": "https://example.com/image.png"},
    "html-link-embed": {"placeholder": "Enter URL to generate HTML embed code...", "example": "https://example.com"},
    "w3c-validator": {"placeholder": "Paste HTML5 to validate syntax...", "example": "<!DOCTYPE html><html><head><title>Test</title></head><body><h1>Hello</h1></body></html>"},

    # ─── DESIGN TOOLS ─────────────────────────────────────────
    "color-picker": {"placeholder": "Enter color as HEX, RGB, or HSL...", "example": "#FF5733"},
    "color-mixer": {"placeholder": "Enter two hex colors to mix (e.g. #FF0000 #0000FF)...", "example": "#FF0000 #0000FF"},
    "color-palette-gen": {"placeholder": "Enter base color (HEX) to generate harmonious palette...", "example": "#3B82F6"},
    "gradient-maker": {"placeholder": "Enter colors or preset name (e.g. sunset, ocean)...", "example": "sunset"},
    "box-shadow-maker": {"placeholder": "Enter preset (default, hard, soft, glow, neumorphism)...", "example": "default"},
    "text-shadow-maker": {"placeholder": "Enter preset or custom value...", "example": "default"},
    "border-radius": {"placeholder": "Enter radius value in px...", "example": "8"},
    "transform-generator": {"placeholder": "Enter value (degrees, scale factor, pixels)...", "example": "45"},
    "transition-generator": {"placeholder": "Describe transition (e.g. color 0.2s ease)...", "example": "color 0.2s ease"},
    "flexbox-playground": {"placeholder": "Describe layout (e.g. centered, space-between)...", "example": "center"},
    "grid-generator": {"placeholder": "Enter number of columns...", "example": "3"},
    "clip-path-generator": {"placeholder": "Describe shape (circle, triangle, pentagon)...", "example": "triangle"},
    "animation-generator": {"placeholder": "Describe animation (e.g. fade-in, slide-up, bounce)...", "example": "fade-in"},
    "font-pairing": {"placeholder": "Optional style preference (modern, classic, elegant)...", "example": ""},
    "aspect-ratio": {"placeholder": "Enter width and height (e.g. 1920, 1080)...", "example": "1920, 1080"},
    "image-dimensions": {"placeholder": "Enter original dimensions and target size...", "example": "1920, 1080"},
    "safe-colors": {"placeholder": "Search for a web-safe color...", "example": ""},
    "material-colors": {"placeholder": "Search for a Material Design color...", "example": "blue"},
    "contrast-checker": {"placeholder": "Enter two hex colors (e.g. #000000 #FFFFFF)...", "example": "#000000 #FFFFFF"},
    "icon-search": {"placeholder": "Search Material Design icons by keyword...", "example": "home"},
    "svg-path-editor": {"placeholder": "Describe shape (circle, rectangle, triangle)...", "example": "circle"},
    "png-compressor": {"placeholder": "Upload PNG image to compress...", "example": ""},
    "svg-optimizer": {"placeholder": "Paste SVG code to optimize...", "example": '<svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="40"/></svg>'},
    "css-cleaner": {"placeholder": "Paste CSS to clean and remove unused rules...", "example": ".a { color: red; } .b { margin: 0; }"},
    "image-filter": {"placeholder": "Upload image to preview CSS filters...", "example": ""},
    "image-to-ascii": {"placeholder": "Enter text to convert to ASCII art...", "example": "HELLO"},
    "ascii-art": {"placeholder": "Enter text to convert to ASCII art...", "example": "HELLO"},
    "text-art": {"placeholder": "Enter text to create decorative text art...", "example": "HELLO"},
    "color-blindness": {"placeholder": "Enter hex color to simulate color blindness...", "example": "#FF5733"},
    "image-metadata": {"placeholder": "Upload image to view EXIF metadata...", "example": ""},
    "favicon-generator": {"placeholder": "Enter initials or emoji for favicon...", "example": "AB"},

    # ─── DEVELOPER TOOLS ──────────────────────────────────────
    "json-schema-gen": {"placeholder": "Paste sample JSON to generate JSON Schema...", "example": '{"name":"John","age":30,"active":true}'},
    "mock-data-gen": {"placeholder": "Enter field types separated by commas (e.g. name, email, phone)...", "example": "name, email, phone"},
    "api-mock-gen": {"placeholder": "Paste JSON response template...", "example": '{"users":[{"id":1,"name":"John"}]}'},
    "diff-viewer": {"placeholder": "Paste first text to compare...", "example": "Hello World\nLine 2"},
    "cron-builder": {"placeholder": "Describe schedule (e.g. every day at 9am, weekdays only)...", "example": "every day at 9am"},
    "jwt-builder": {"placeholder": "Paste payload JSON to build JWT...", "example": '{"user":"john","role":"admin"}'},
    "color-to-tailwind": {"placeholder": "Enter color values for Tailwind config...", "example": "#3B82F6"},
    "html-to-jsx": {"placeholder": "Paste HTML to convert to React JSX...", "example": '<div className="box"><p>Hello</p></div>'},
    "jsx-to-html": {"placeholder": "Paste JSX to convert to HTML...", "example": '<div className="box"><p>Hello</p></div>'},
    "css-to-js": {"placeholder": "Paste CSS rules to convert to JS objects...", "example": ".box { color: red; margin: 10px; }"},
    "js-to-css": {"placeholder": "Paste JS style object to convert to CSS...", "example": ""},
    "html-entity-list": {"placeholder": "Search for HTML entities...", "example": "amp"},
    "ascii-table-full": {"placeholder": "Search ASCII character...", "example": ""},
    "unicode-table": {"placeholder": "Search Unicode characters...", "example": "heart"},
    "regex-cheatsheet": {"placeholder": "Search regex patterns...", "example": ""},
    "linux-cheatsheet": {"placeholder": "Search Linux commands...", "example": "grep"},
    "git-cheatsheet": {"placeholder": "Search Git commands...", "example": "commit"},
    "docker-cheatsheet": {"placeholder": "Search Docker commands...", "example": "run"},
    "sql-cheatsheet": {"placeholder": "Search SQL syntax...", "example": "JOIN"},
    "python-cheatsheet": {"placeholder": "Search Python syntax...", "example": "list comprehension"},
    "javascript-cheatsheet": {"placeholder": "Search JavaScript features...", "example": "arrow function"},
    "react-cheatsheet": {"placeholder": "Search React hooks and patterns...", "example": "useState"},
    "css-flexbox-cheat": {"placeholder": "Search Flexbox properties...", "example": "justify-content"},
    "css-grid-cheat": {"placeholder": "Search CSS Grid properties...", "example": "grid-template"},
    "http-status": {"placeholder": "Search HTTP status codes...", "example": "404"},
    "error-code-ref": {"placeholder": "Search error codes...", "example": "TypeError"},
    "date-format-ref": {"placeholder": "Search date format patterns...", "example": "%Y-%m-%d"},
    "timezone-list": {"placeholder": "Search timezones...", "example": "UTC+5:30"},
    "emoji-list": {"placeholder": "Search emojis...", "example": "heart"},
    "markdown-cheatsheet": {"placeholder": "Search Markdown syntax...", "example": "heading"},

    # ─── ENCODING TOOLS ───────────────────────────────────────
    "base64-tool": {"placeholder": "Enter text or Base64 string to encode/decode...", "example": "Hello World"},
    "url-encode-tool": {"placeholder": "Enter URL component to encode/decode...", "example": "hello world&key=value"},
    "html-entity-tool": {"placeholder": "Enter text with special characters...", "example": "<div>Hello & Welcome</div>"},
    "hex-encode-tool": {"placeholder": "Enter text or hex to convert...", "example": "Hello"},
    "binary-encode-tool": {"placeholder": "Enter text or binary to convert...", "example": "Hello"},
    "octal-encode-tool": {"placeholder": "Enter text or octal to convert...", "example": "Hello"},
    "unicode-encode": {"placeholder": "Enter text or Unicode escapes...", "example": "Hello 你好"},
    "punycode-tool": {"placeholder": "Enter international domain name...", "example": "münchen.de"},
    "morse-encoder": {"placeholder": "Enter text to encode as Morse code...", "example": "SOS"},
    "morse-decoder": {"placeholder": "Enter Morse code to decode (use dots and dashes)...", "example": "... --- ..."},
    "pig-latin-tool": {"placeholder": "Enter English text to translate to Pig Latin...", "example": "hello world"},
    "reverse-text-tool": {"placeholder": "Enter text to reverse...", "example": "Hello World"},
    "bubble-text": {"placeholder": "Enter text to style as bubble text...", "example": "HELLO"},
    "fancy-text": {"placeholder": "Enter text to stylize with Unicode fonts...", "example": "Hello World"},
    "cipher-wheel": {"placeholder": "Enter text to encrypt/decrypt with Caesar cipher...", "example": "Hello World"},
    "substitution-cipher": {"placeholder": "Enter text to encrypt with substitution...", "example": "ATTACK AT DAWN"},
    "transposition-cipher": {"placeholder": "Enter text to encrypt with transposition...", "example": "HELLO WORLD"},
    "brute-force-decoder": {"placeholder": "Enter ciphertext to try all 25 Caesar shifts...", "example": "Khoor Zruog"},
    "hash-lookup": {"placeholder": "Enter hash to search known databases...", "example": "5d41402abc4b2a76b9719d911017c592"},
    "password-checker": {"placeholder": "Enter password to analyze quality...", "example": "MyP@ssw0rd123!"},
    "passphrase-gen": {"placeholder": "Optional word count...", "example": ""},
    "random-bytes": {"placeholder": "Enter byte count...", "example": "32"},
    "encoding-detector": {"placeholder": "Paste text to detect encoding...", "example": "Hello World 你好"},
    "utf8-validator": {"placeholder": "Paste text to validate UTF-8...", "example": "Hello World"},
    "idn-converter": {"placeholder": "Enter internationalized domain name...", "example": "münchen.de"},
    "slash-escape": {"placeholder": "Enter string to escape for JS, Python, JSON, SQL...", "example": "Hello \"World\" it's a test"},
    "character-map": {"placeholder": "Search ASCII characters...", "example": ""},
    "base-n-converter": {"placeholder": "Enter number and base (e.g. 255 from base 10)...", "example": "255"},
    "encoding-chains": {"placeholder": "Enter text to encode through multiple layers...", "example": "secret"},

    # ─── CONVERTER TOOLS ──────────────────────────────────────
    "text-to-html": {"placeholder": "Enter plain text to convert to HTML...", "example": "Hello World\nThis is a paragraph."},
    "html-to-text": {"placeholder": "Paste HTML to extract plain text...", "example": "<p>Hello <b>World</b></p>"},
    "text-to-css": {"placeholder": "Enter text to generate CSS styles for...", "example": "Hello World"},
    "text-to-svg": {"placeholder": "Enter text to convert to SVG...", "example": "Hello"},
    "csv-to-markdown": {"placeholder": "Paste CSV data to convert to Markdown table...", "example": "Name,Age,City\nJohn,30,NYC\nJane,25,LA"},
    "markdown-to-csv": {"placeholder": "Paste Markdown table to convert to CSV...", "example": "| Name | Age |\n|------|-----|\n| John | 30 |"},
    "json-to-yaml": {"placeholder": "Paste JSON to convert to YAML...", "example": '{"name":"John","age":30,"city":"NYC"}'},
    "yaml-to-json": {"placeholder": "Paste YAML to convert to JSON...", "example": "name: John\nage: 30\ncity: NYC"},
    "json-to-toml": {"placeholder": "Paste JSON to convert to TOML...", "example": '{"server":{"host":"0.0.0.0","port":8080}}'},
    "toml-to-json": {"placeholder": "Paste TOML to convert to JSON...", "example": "[server]\nhost = \"0.0.0.0\"\nport = 8080"},
    "json-to-typescript": {"placeholder": "Paste JSON to generate TypeScript interface...", "example": '{"name":"John","age":30,"active":true}'},
    "json-to-python": {"placeholder": "Paste JSON to generate Python dataclass...", "example": '{"name":"John","age":30}'},
    "json-to-go-struct": {"placeholder": "Paste JSON to generate Go struct...", "example": '{"name":"John","age":30}'},
    "json-to-sql": {"placeholder": "Paste JSON array to generate SQL INSERT...", "example": '[{"name":"John","age":30}]'},
    "csv-to-sql": {"placeholder": "Paste CSV to generate SQL CREATE + INSERT...", "example": "name,age\nJohn,30\nJane,25"},
    "xml-to-yaml": {"placeholder": "Paste XML to convert to YAML...", "example": "<person><name>John</name></person>"},
    "yaml-to-xml": {"placeholder": "Paste YAML to convert to XML...", "example": "person:\n  name: John"},
    "regex-to-nfa": {"placeholder": "Enter regex pattern to visualize as NFA...", "example": "(a|b)*abb"},
    "cron-parser": {"placeholder": "Enter cron expression to parse...", "example": "0 9 * * 1-5"},
    "timezone-converter": {"placeholder": "Enter time and timezone to convert...", "example": "14:00 UTC"},
    "emoji-to-text": {"placeholder": "Enter emoji to get text description...", "example": "😀🎉❤️"},
    "number-to-words": {"placeholder": "Enter number to convert to words...", "example": "12345"},
    "words-to-number": {"placeholder": "Enter written number (e.g. one hundred twenty three)...", "example": "forty two"},
    "roman-to-arabic": {"placeholder": "Enter Roman numeral to convert...", "example": "XLII"},
    "arabic-to-roman": {"placeholder": "Enter number (1-3999) to convert to Roman...", "example": "42"},
    "color-to-css": {"placeholder": "Enter color value to convert to CSS...", "example": "#FF5733"},
    "css-to-text": {"placeholder": "Paste CSS to convert to readable text...", "example": ".a { color: red; margin: 10px; }"},
    "image-to-base64": {"placeholder": "Upload image or paste Base64 to decode...", "example": ""},
    "text-to-image": {"placeholder": "Enter text to render as image...", "example": "Hello World"},
    "font-converter": {"placeholder": "Enter font name for CSS declaration...", "example": "Roboto"},
    "svg-to-css": {"placeholder": "Paste SVG to convert to CSS background...", "example": '<svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="40"/></svg>'},
    "json-to-env": {"placeholder": "Paste JSON config to convert to .env format...", "example": '{"DB_HOST":"localhost","DB_PORT":5432}'},
    "env-to-json": {"placeholder": "Paste .env variables to convert to JSON...", "example": "DB_HOST=localhost\nDB_PORT=5432"},
    "sql-to-json": {"placeholder": "Paste SQL CREATE TABLE to generate JSON schema...", "example": "CREATE TABLE users (id INT, name VARCHAR(100));"},
    "graphql-to-rest": {"placeholder": "Paste GraphQL query to generate REST description...", "example": "query { users { id name email } }"},
    "html-to-markdown": {"placeholder": "Paste HTML to convert to Markdown...", "example": "<h1>Title</h1><p>Paragraph</p>"},
    "markdown-to-html": {"placeholder": "Paste Markdown to convert to HTML...", "example": "# Title\n\nParagraph with **bold**."},
    "markdown-to-csv": {"placeholder": "Paste Markdown table to convert to CSV...", "example": "| Name | Age |\n|------|-----|\n| John | 30 |"},
    "csv-to-markdown": {"placeholder": "Paste CSV to convert to Markdown table...", "example": "Name,Age\nJohn,30"},
}

# Default configs for tools without specific overrides
DEFAULTS = {
    "text": {"result_mode": "text"},
    "url": {"result_mode": "text"},
    "select": {"result_mode": "text"},
    "number": {"result_mode": "text"},
}

updated = 0
for slug, overrides in UPDATES.items():
    tj = os.path.join(TOOLS_DIR, slug, "tool.json")
    if not os.path.isfile(tj):
        continue
    with open(tj, encoding="utf-8") as f:
        tool = json.load(f)

    # Apply overrides
    for k, v in overrides.items():
        if k == "placeholder":
            tool["placeholder"] = v
        elif k == "example":
            tool["example"] = v
        elif k in ("processor", "inputs", "result_mode"):
            if "config" not in tool:
                tool["config"] = {}
            tool["config"][k] = v

    with open(tj, "w", encoding="utf-8") as f:
        json.dump(tool, f, indent=4)
    updated += 1

print(f"Updated {updated} tools with examples and placeholders")
